# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.CommunityCommunityLiveStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"dateStatusUpdated",
    :"url",
    :"partnershipIdentifier",
    :"partnershipType",
    :"thumbnail",
    :"thumbnailSmall",
    :"thumbnailLarge",
    :"destinyCharacterId",
    :"userInfo",
    :"currentActivityHash",
    :"dateLastPlayed",
    :"dateStreamStarted",
    :"locale",
    :"currentViewers",
    :"followers",
    :"overallViewers",
    :"isFeatured",
    :"title",
    :"activityModeHash",
    :"dateFeatured",
    :"trendingValue",
    :"isSubscribable"
  ]

  @type t :: %__MODULE__{
    :"dateStatusUpdated" => DateTime.t,
    :"url" => String.t,
    :"partnershipIdentifier" => String.t,
    :"partnershipType" => PartnershipsPartnershipType,
    :"thumbnail" => String.t,
    :"thumbnailSmall" => String.t,
    :"thumbnailLarge" => String.t,
    :"destinyCharacterId" => integer(),
    :"userInfo" => UserUserInfoCard,
    :"currentActivityHash" => integer(),
    :"dateLastPlayed" => DateTime.t,
    :"dateStreamStarted" => DateTime.t,
    :"locale" => String.t,
    :"currentViewers" => integer(),
    :"followers" => integer(),
    :"overallViewers" => integer(),
    :"isFeatured" => boolean(),
    :"title" => String.t,
    :"activityModeHash" => integer(),
    :"dateFeatured" => DateTime.t,
    :"trendingValue" => float(),
    :"isSubscribable" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.CommunityCommunityLiveStatus do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"partnershipType", :struct, BungieNetAPI.Model.PartnershipsPartnershipType, options)
    |> deserialize(:"userInfo", :struct, BungieNetAPI.Model.UserUserInfoCard, options)
  end
end

