# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ComponentsComponentResponse do
  @moduledoc """
  The base class for any component-returning object that may need to indicate information about the state of the component being returned.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"privacy"
  ]

  @type t :: %__MODULE__{
    :"privacy" => ComponentsComponentPrivacySetting
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ComponentsComponentResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"privacy", :struct, BungieNetAPI.Model.ComponentsComponentPrivacySetting, options)
  end
end

