# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ComponentsComponentPrivacySetting do
  @moduledoc """
  A set of flags for reason(s) why the component populated in the way that it did. Inspect the individual flags for the reasons.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ComponentsComponentPrivacySetting do
  def decode(value, _options) do
    value
  end
end

