# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ConfigGroupTheme do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"folder",
    :"description"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"folder" => String.t,
    :"description" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ConfigGroupTheme do
  def decode(value, _options) do
    value
  end
end

