# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ConfigUserTheme do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userThemeId",
    :"userThemeName",
    :"userThemeDescription"
  ]

  @type t :: %__MODULE__{
    :"userThemeId" => integer(),
    :"userThemeName" => String.t,
    :"userThemeDescription" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ConfigUserTheme do
  def decode(value, _options) do
    value
  end
end

