# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ContentContentRepresentation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"path",
    :"validationString"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"path" => String.t,
    :"validationString" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ContentContentRepresentation do
  def decode(value, _options) do
    value
  end
end

