# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ContentContentItemPublicContract do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"contentId",
    :"cType",
    :"cmsPath",
    :"creationDate",
    :"modifyDate",
    :"allowComments",
    :"hasAgeGate",
    :"minimumAge",
    :"ratingImagePath",
    :"author",
    :"autoEnglishPropertyFallback",
    :"properties",
    :"representations",
    :"tags",
    :"commentSummary"
  ]

  @type t :: %__MODULE__{
    :"contentId" => integer(),
    :"cType" => String.t,
    :"cmsPath" => String.t,
    :"creationDate" => DateTime.t,
    :"modifyDate" => DateTime.t,
    :"allowComments" => boolean(),
    :"hasAgeGate" => boolean(),
    :"minimumAge" => integer(),
    :"ratingImagePath" => String.t,
    :"author" => UserGeneralUser,
    :"autoEnglishPropertyFallback" => boolean(),
    :"properties" => %{optional(String.t) => Object},
    :"representations" => [ContentContentRepresentation],
    :"tags" => [String.t],
    :"commentSummary" => ContentCommentSummary
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ContentContentItemPublicContract do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"author", :struct, BungieNetAPI.Model.UserGeneralUser, options)
    |> deserialize(:"properties", :map, BungieNetAPI.Model.Object, options)
    |> deserialize(:"representations", :list, BungieNetAPI.Model.ContentContentRepresentation, options)
    |> deserialize(:"commentSummary", :struct, BungieNetAPI.Model.ContentCommentSummary, options)
  end
end

