# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DatesDateRange do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"start",
    :"end"
  ]

  @type t :: %__MODULE__{
    :"start" => DateTime.t,
    :"end" => DateTime.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DatesDateRange do
  def decode(value, _options) do
    value
  end
end

