# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalStatsActivity do
  @moduledoc """
  Summary information about the activity that was played.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"referenceId",
    :"directorActivityHash",
    :"instanceId",
    :"mode",
    :"modes",
    :"isPrivate"
  ]

  @type t :: %__MODULE__{
    :"referenceId" => integer(),
    :"directorActivityHash" => integer(),
    :"instanceId" => integer(),
    :"mode" => Object,
    :"modes" => [DestinyHistoricalStatsDefinitionsDestinyActivityModeType],
    :"isPrivate" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalStatsActivity do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mode", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"modes", :list, BungieNetAPI.Model.DestinyHistoricalStatsDefinitionsDestinyActivityModeType, options)
  end
end

