# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyProgressionStepDefinition do
  @moduledoc """
  This defines a single Step in a progression (which roughly equates to a level. See DestinyProgressionDefinition for caveats).
  """

  @derive [Poison.Encoder]
  defstruct [
    :"stepName",
    :"displayEffectType",
    :"progressTotal",
    :"rewardItems"
  ]

  @type t :: %__MODULE__{
    :"stepName" => String.t,
    :"displayEffectType" => Object,
    :"progressTotal" => integer(),
    :"rewardItems" => [DestinyDestinyItemQuantity]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyProgressionStepDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayEffectType", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"rewardItems", :list, BungieNetAPI.Model.DestinyDestinyItemQuantity, options)
  end
end

