# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition do
  @moduledoc """
  Data related to what happens while a plug is being inserted, mostly for UI purposes.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"actionExecuteSeconds",
    :"actionType"
  ]

  @type t :: %__MODULE__{
    :"actionExecuteSeconds" => integer(),
    :"actionType" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsSocketsDestinyInsertPlugActionDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"actionType", :struct, BungieNetAPI.Model.Object, options)
  end
end

