# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEquipFailureReason do
  @moduledoc """
  The reasons why an item cannot be equipped, if any. Many flags can be set, or \&quot;None\&quot; if
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEquipFailureReason do
  def decode(value, _options) do
    value
  end
end

