# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyActivitiesDestinyPublicActivityStatus do
  @moduledoc """
  Represents the public-facing status of an activity: any data about what is currently active in the Activity, regardless of an individual character&#39;s progress in it.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"challengeObjectiveHashes",
    :"modifierHashes",
    :"rewardTooltipItems"
  ]

  @type t :: %__MODULE__{
    :"challengeObjectiveHashes" => [integer()],
    :"modifierHashes" => [integer()],
    :"rewardTooltipItems" => [DestinyDestinyItemQuantity]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyActivitiesDestinyPublicActivityStatus do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"rewardTooltipItems", :list, BungieNetAPI.Model.DestinyDestinyItemQuantity, options)
  end
end

