# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDestinyProgressionStepDisplayEffect do
  @moduledoc """
  If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDestinyProgressionStepDisplayEffect do
  def decode(value, _options) do
    value
  end
end

