# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyLocationDefinition do
  @moduledoc """
  A \&quot;Location\&quot; is a sort of shortcut for referring to a specific combination of Activity, Destination, Place, and even Bubble or NavPoint within a space.  Most of this data isn&#39;t intrinsically useful to us, but Objectives refer to locations, and through that we can at least infer the Activity, Destination, and Place being referred to by the Objective.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendorHash",
    :"locationReleases",
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"vendorHash" => integer(),
    :"locationReleases" => [DestinyDefinitionsDestinyLocationReleaseDefinition],
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyLocationDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"locationReleases", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyLocationReleaseDefinition, options)
  end
end

