# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneActivityVariant do
  @moduledoc """
  Represents custom data that we know about an individual variant of an activity.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"activityHash",
    :"completionStatus",
    :"activityModeHash",
    :"activityModeType"
  ]

  @type t :: %__MODULE__{
    :"activityHash" => integer(),
    :"completionStatus" => Object,
    :"activityModeHash" => integer(),
    :"activityModeType" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneActivityVariant do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"completionStatus", :struct, BungieNetAPI.Model.Object, options)
  end
end

