# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsSourcesDestinyItemSourceDefinition do
  @moduledoc """
  Properties of a DestinyInventoryItemDefinition that store all of the information we were able to discern about how the item spawns, and where you can find the item.  Items will have many of these sources, one per level at which it spawns, to try and give more granular data about where items spawn for specific level ranges.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"level",
    :"minQuality",
    :"maxQuality",
    :"minLevelRequired",
    :"maxLevelRequired",
    :"computedStats",
    :"sourceHashes"
  ]

  @type t :: %__MODULE__{
    :"level" => integer(),
    :"minQuality" => integer(),
    :"maxQuality" => integer(),
    :"minLevelRequired" => integer(),
    :"maxLevelRequired" => integer(),
    :"computedStats" => %{optional(String.t) => DestinyDefinitionsDestinyInventoryItemStatDefinition},
    :"sourceHashes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsSourcesDestinyItemSourceDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"computedStats", :map, BungieNetAPI.Model.DestinyDefinitionsDestinyInventoryItemStatDefinition, options)
  end
end

