# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionDefinition do
  @moduledoc """
  A Vendor Interaction is a dialog shown by the vendor other than sale items or transfer screens. The vendor is showing you something, and asking you to reply to it by choosing an option or reward.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"replies",
    :"vendorCategoryIndex",
    :"questlineItemHash",
    :"sackInteractionList",
    :"uiInteractionType",
    :"rewardBlockLabel",
    :"rewardVendorCategoryIndex",
    :"flavorLineOne",
    :"flavorLineTwo",
    :"headerDisplayProperties",
    :"instructions"
  ]

  @type t :: %__MODULE__{
    :"replies" => [DestinyDefinitionsDestinyVendorInteractionReplyDefinition],
    :"vendorCategoryIndex" => integer(),
    :"questlineItemHash" => integer(),
    :"sackInteractionList" => [DestinyDefinitionsDestinyVendorInteractionSackEntryDefinition],
    :"uiInteractionType" => integer(),
    :"rewardBlockLabel" => String.t,
    :"rewardVendorCategoryIndex" => integer(),
    :"flavorLineOne" => String.t,
    :"flavorLineTwo" => String.t,
    :"headerDisplayProperties" => Object,
    :"instructions" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"replies", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionReplyDefinition, options)
    |> deserialize(:"sackInteractionList", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionSackEntryDefinition, options)
    |> deserialize(:"headerDisplayProperties", :struct, BungieNetAPI.Model.Object, options)
  end
end

