# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition do
  @moduledoc """
  When a Graph needs to show active Objectives, this defines those objectives as well as an identifier.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"objectiveHash"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"objectiveHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphDisplayObjectiveDefinition do
  def decode(value, _options) do
    value
  end
end

