# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDestinyGameVersions do
  @moduledoc """
  A flags enumeration indicating the versions of the game that a given user has purchased.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDestinyGameVersions do
  def decode(value, _options) do
    value
  end
end

