# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketBlockDefinition do
  @moduledoc """
  If defined, the item has at least one socket.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"detail",
    :"socketEntries",
    :"intrinsicSockets",
    :"socketCategories"
  ]

  @type t :: %__MODULE__{
    :"detail" => String.t,
    :"socketEntries" => [DestinyDefinitionsDestinyItemSocketEntryDefinition],
    :"intrinsicSockets" => [DestinyDefinitionsDestinyItemIntrinsicSocketEntryDefinition],
    :"socketCategories" => [DestinyDefinitionsDestinyItemSocketCategoryDefinition]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketBlockDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"socketEntries", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketEntryDefinition, options)
    |> deserialize(:"intrinsicSockets", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyItemIntrinsicSocketEntryDefinition, options)
    |> deserialize(:"socketCategories", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketCategoryDefinition, options)
  end
end

