# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemSummaryBlockDefinition do
  @moduledoc """
  This appears to be information used when rendering rewards. We don&#39;t currently use it on BNet.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sortPriority"
  ]

  @type t :: %__MODULE__{
    :"sortPriority" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemSummaryBlockDefinition do
  def decode(value, _options) do
    value
  end
end

