# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyTalentNodeCategory do
  @moduledoc """
  An artificial construct provided by Bungie.Net, where we attempt to group talent nodes by functionality.  This is a single set of references to Talent Nodes that share a common trait or purpose.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"identifier",
    :"isLoreDriven",
    :"displayProperties",
    :"nodeHashes"
  ]

  @type t :: %__MODULE__{
    :"identifier" => String.t,
    :"isLoreDriven" => boolean(),
    :"displayProperties" => Object,
    :"nodeHashes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyTalentNodeCategory do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.Object, options)
  end
end

