# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyStatGroupDefinition do
  @moduledoc """
  When an inventory item (DestinyInventoryItemDefinition) has Stats (such as Attack Power), the item will refer to a Stat Group. This definition enumerates the properties used to transform the item&#39;s \&quot;Investment\&quot; stats into \&quot;Display\&quot; stats.  See DestinyStatDefinition&#39;s documentation for information about the transformation of Stats, and the meaning of an Investment vs. a Display stat.  If you don&#39;t want to do these calculations on your own, fear not: pulling live data from the BNet endpoints will return display stat values pre-computed and ready for you to use. I highly recommend this approach, saves a lot of time and also accounts for certain stat modifiers that can&#39;t easily be accounted for without live data (such as stat modifiers on Talent Grids and Socket Plugs)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"maximumValue",
    :"uiPosition",
    :"scaledStats",
    :"overrides",
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"maximumValue" => integer(),
    :"uiPosition" => integer(),
    :"scaledStats" => [DestinyDefinitionsDestinyStatDisplayDefinition],
    :"overrides" => %{optional(String.t) => DestinyDefinitionsDestinyStatOverrideDefinition},
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyStatGroupDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"scaledStats", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyStatDisplayDefinition, options)
    |> deserialize(:"overrides", :map, BungieNetAPI.Model.DestinyDefinitionsDestinyStatOverrideDefinition, options)
  end
end

