# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsReportingDestinyReportReasonDefinition do
  @moduledoc """
  A specific reason for being banned. Only accessible under the related category (DestinyReportReasonCategoryDefinition) under which it is shown. Note that this means that report reasons&#39; reasonHash are not globally unique: and indeed, entries like \&quot;Other\&quot; are defined under most categories for example.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reasonHash",
    :"displayProperties"
  ]

  @type t :: %__MODULE__{
    :"reasonHash" => integer(),
    :"displayProperties" => DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsReportingDestinyReportReasonDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition, options)
  end
end

