# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorCategory do
  @moduledoc """
  Information about the category and items currently sold in that category.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categoryIndex",
    :"itemIndexes"
  ]

  @type t :: %__MODULE__{
    :"categoryIndex" => integer(),
    :"itemIndexes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorCategory do
  def decode(value, _options) do
    value
  end
end

