# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyActivityGuidedBlockDefinition do
  @moduledoc """
  Guided Game information for this activity.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"guidedMaxLobbySize",
    :"guidedMinLobbySize",
    :"guidedDisbandCount"
  ]

  @type t :: %__MODULE__{
    :"guidedMaxLobbySize" => integer(),
    :"guidedMinLobbySize" => integer(),
    :"guidedDisbandCount" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyActivityGuidedBlockDefinition do
  def decode(value, _options) do
    value
  end
end

