# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition do
  @moduledoc """
  Any data we need to figure out whether this Quest Item is the currently active one for the conceptual Milestone. Even just typing this description, I already regret it.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"questItemHash",
    :"displayProperties",
    :"overrideImage",
    :"questRewards",
    :"activities"
  ]

  @type t :: %__MODULE__{
    :"questItemHash" => integer(),
    :"displayProperties" => Object,
    :"overrideImage" => String.t,
    :"questRewards" => Object,
    :"activities" => %{optional(String.t) => DestinyDefinitionsMilestonesDestinyMilestoneActivityDefinition}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneQuestDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"questRewards", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"activities", :map, BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneActivityDefinition, options)
  end
end

