# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemGearsetBlockDefinition do
  @moduledoc """
  If an item has a related gearset, this is the list of items in that set, and an unlock expression that evaluates to a number representing the progress toward gearset completion (a very rare use for unlock expressions!)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"trackingValueMax",
    :"itemList"
  ]

  @type t :: %__MODULE__{
    :"trackingValueMax" => integer(),
    :"itemList" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemGearsetBlockDefinition do
  def decode(value, _options) do
    value
  end
end

