# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyFactionDefinition do
  @moduledoc """
  These definitions represent Factions in the game. Factions have ended up unilaterally being related to Vendors that represent them, but that need not necessarily be the case.  A Faction is really just an entity that has a related progression for which a character can gain experience. In Destiny 1, Dead Orbit was an example of a Faction: there happens to be a Vendor that represents Dead Orbit (and indeed, DestinyVendorDefinition.factionHash defines to this relationship), but Dead Orbit could theoretically exist without the Vendor that provides rewards.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayProperties",
    :"progressionHash",
    :"tokenValues",
    :"rewardItemHash",
    :"rewardVendorHash",
    :"vendors",
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"displayProperties" => DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition,
    :"progressionHash" => integer(),
    :"tokenValues" => %{optional(String.t) => integer()},
    :"rewardItemHash" => integer(),
    :"rewardVendorHash" => integer(),
    :"vendors" => [DestinyDefinitionsDestinyFactionVendorDefinition],
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyFactionDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition, options)
    |> deserialize(:"vendors", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyFactionVendorDefinition, options)
  end
end

