# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsCommonDestinyPositionDefinition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"x",
    :"y",
    :"z"
  ]

  @type t :: %__MODULE__{
    :"x" => integer(),
    :"y" => integer(),
    :"z" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsCommonDestinyPositionDefinition do
  def decode(value, _options) do
    value
  end
end

