# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemSocketsComponent do
  @moduledoc """
  Instanced items can have sockets, which are slots on the item where plugs can be inserted.  Sockets are a bit complex: be sure to examine the documentation on the DestinyInventoryItemDefinition&#39;s \&quot;socket\&quot; block and elsewhere on these objects for more details.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sockets"
  ]

  @type t :: %__MODULE__{
    :"sockets" => [DestinyEntitiesItemsDestinyItemSocketState]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemSocketsComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sockets", :list, BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemSocketState, options)
  end
end

