# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyMaterialRequirement do
  @moduledoc """
  Many actions relating to items require you to expend materials: - Activating a talent node - Inserting a plug into a socket The items will refer to material requirements by a materialRequirementsHash in these cases, and this is the definition for those requirements in terms of the item required, how much of it is required and other interesting info. This is one of the rare/strange times where a single contract class is used both in definitions *and* in live data response contracts. I&#39;m not sure yet whether I regret that.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemHash",
    :"deleteOnAction",
    :"count",
    :"omitFromRequirements"
  ]

  @type t :: %__MODULE__{
    :"itemHash" => integer(),
    :"deleteOnAction" => boolean(),
    :"count" => integer(),
    :"omitFromRequirements" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyMaterialRequirement do
  def decode(value, _options) do
    value
  end
end

