# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneRewardEntry do
  @moduledoc """
  The character-specific data for a milestone&#39;s reward entry. See DestinyMilestoneDefinition for more information about Reward Entries.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rewardEntryHash",
    :"earned",
    :"redeemed"
  ]

  @type t :: %__MODULE__{
    :"rewardEntryHash" => integer(),
    :"earned" => boolean(),
    :"redeemed" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneRewardEntry do
  def decode(value, _options) do
    value
  end
end

