# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyInventoryItemStatDefinition do
  @moduledoc """
  Defines a specific stat value on an item, and the minimum/maximum range that we could compute for the item based on our heuristics for how the item might be generated.  Not guaranteed to match real-world instances of the item, but should hopefully at least be close. If it&#39;s not close, let us know on the Bungie API forums.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"statHash",
    :"value",
    :"minimum",
    :"maximum"
  ]

  @type t :: %__MODULE__{
    :"statHash" => integer(),
    :"value" => integer(),
    :"minimum" => integer(),
    :"maximum" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyInventoryItemStatDefinition do
  def decode(value, _options) do
    value
  end
end

