# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneVendor do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendorHash",
    :"previewItemHash"
  ]

  @type t :: %__MODULE__{
    :"vendorHash" => integer(),
    :"previewItemHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneVendor do
  def decode(value, _options) do
    value
  end
end

