# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyProgressionDisplayPropertiesDefinition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayUnitsName",
    :"description",
    :"name",
    :"icon",
    :"hasIcon"
  ]

  @type t :: %__MODULE__{
    :"displayUnitsName" => String.t,
    :"description" => String.t,
    :"name" => String.t,
    :"icon" => String.t,
    :"hasIcon" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyProgressionDisplayPropertiesDefinition do
  def decode(value, _options) do
    value
  end
end

