# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDestinyPostGameCarnageReportData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"period",
    :"activityDetails",
    :"entries",
    :"teams"
  ]

  @type t :: %__MODULE__{
    :"period" => DateTime.t,
    :"activityDetails" => Object,
    :"entries" => [DestinyHistoricalStatsDestinyPostGameCarnageReportEntry],
    :"teams" => [DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDestinyPostGameCarnageReportData do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"activityDetails", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"entries", :list, BungieNetAPI.Model.DestinyHistoricalStatsDestinyPostGameCarnageReportEntry, options)
    |> deserialize(:"teams", :list, BungieNetAPI.Model.DestinyHistoricalStatsDestinyPostGameCarnageReportTeamEntry, options)
  end
end

