# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneQuest do
  @moduledoc """
  If a Milestone has one or more Quests, this will contain the live information for the character&#39;s status with one of those quests.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"questItemHash",
    :"status",
    :"activity",
    :"challenges"
  ]

  @type t :: %__MODULE__{
    :"questItemHash" => integer(),
    :"status" => Object,
    :"activity" => Object,
    :"challenges" => [DestinyChallengesDestinyChallengeStatus]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneQuest do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"activity", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"challenges", :list, BungieNetAPI.Model.DestinyChallengesDestinyChallengeStatus, options)
  end
end

