# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneContent do
  @moduledoc """
  Represents localized, extended content related to Milestones. This is intentionally returned by a separate endpoint and not with Character-level Milestone data because we do not put localized data into standard Destiny responses, both for brevity of response and for caching purposes. If you really need this data, hit the Milestone Content endpoint.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"about",
    :"status",
    :"tips",
    :"itemCategories"
  ]

  @type t :: %__MODULE__{
    :"about" => String.t,
    :"status" => String.t,
    :"tips" => [String.t],
    :"itemCategories" => [DestinyMilestonesDestinyMilestoneContentItemCategory]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneContent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"itemCategories", :list, BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneContentItemCategory, options)
  end
end

