# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorDisplayPropertiesDefinition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"largeIcon",
    :"subtitle",
    :"originalIcon",
    :"requirementsDisplay",
    :"description",
    :"name",
    :"icon",
    :"hasIcon"
  ]

  @type t :: %__MODULE__{
    :"largeIcon" => String.t,
    :"subtitle" => String.t,
    :"originalIcon" => String.t,
    :"requirementsDisplay" => [DestinyDefinitionsDestinyVendorRequirementDisplayEntryDefinition],
    :"description" => String.t,
    :"name" => String.t,
    :"icon" => String.t,
    :"hasIcon" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorDisplayPropertiesDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"requirementsDisplay", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyVendorRequirementDisplayEntryDefinition, options)
  end
end

