# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyComponentsKiosksDestinyKioskItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"index",
    :"canAcquire",
    :"failureIndexes",
    :"flavorObjective"
  ]

  @type t :: %__MODULE__{
    :"index" => integer(),
    :"canAcquire" => boolean(),
    :"failureIndexes" => [integer()],
    :"flavorObjective" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyComponentsKiosksDestinyKioskItem do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"flavorObjective", :struct, BungieNetAPI.Model.Object, options)
  end
end

