# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemSocketState do
  @moduledoc """
  The status of a given item&#39;s socket. (which plug is inserted, if any: whether it is enabled, what \&quot;reusable\&quot; plugs can be inserted, etc...)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"plugHash",
    :"isEnabled",
    :"enableFailIndexes",
    :"reusablePlugHashes",
    :"plugObjectives",
    :"reusablePlugs"
  ]

  @type t :: %__MODULE__{
    :"plugHash" => integer(),
    :"isEnabled" => boolean(),
    :"enableFailIndexes" => [integer()],
    :"reusablePlugHashes" => [integer()],
    :"plugObjectives" => [DestinyQuestsDestinyObjectiveProgress],
    :"reusablePlugs" => [DestinySocketsDestinyItemPlug]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemSocketState do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plugObjectives", :list, BungieNetAPI.Model.DestinyQuestsDestinyObjectiveProgress, options)
    |> deserialize(:"reusablePlugs", :list, BungieNetAPI.Model.DestinySocketsDestinyItemPlug, options)
  end
end

