# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyGearArtArrangementReference do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"classHash",
    :"artArrangementHash"
  ]

  @type t :: %__MODULE__{
    :"classHash" => integer(),
    :"artArrangementHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyGearArtArrangementReference do
  def decode(value, _options) do
    value
  end
end

