# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyObjectiveDefinition do
  @moduledoc """
  Defines an \&quot;Objective\&quot;.  An objective is a specific task you should accomplish in the game. These are referred to by:  - Quest Steps (which are DestinyInventoryItemDefinition entities with Objectives)  - Challenges (which are Objectives defined on an DestinyActivityDefintion)  - Milestones (which refer to Objectives that are defined on both Quest Steps and Activities)  - Anything else that the designers decide to do later.  Objectives have progress, a notion of having been Completed, human readable data describing the task to be accomplished, and a lot of optional tack-on data that can enhance the information provided about the task.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayProperties",
    :"completionValue",
    :"locationHash",
    :"allowNegativeValue",
    :"allowValueChangeWhenCompleted",
    :"isCountingDownward",
    :"valueStyle",
    :"progressDescription",
    :"perks",
    :"stats",
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"displayProperties" => Object,
    :"completionValue" => integer(),
    :"locationHash" => integer(),
    :"allowNegativeValue" => boolean(),
    :"allowValueChangeWhenCompleted" => boolean(),
    :"isCountingDownward" => boolean(),
    :"valueStyle" => Object,
    :"progressDescription" => String.t,
    :"perks" => Object,
    :"stats" => Object,
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyObjectiveDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"valueStyle", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"perks", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"stats", :struct, BungieNetAPI.Model.Object, options)
  end
end

