# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphArtElementDefinition do
  @moduledoc """
  These Art Elements are meant to represent one-off visual effects overlaid on the map. Currently, we do not have a pipeline to import the assets for these overlays, so this info exists as a placeholder for when such a pipeline exists (if it ever will)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"position"
  ]

  @type t :: %__MODULE__{
    :"position" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphArtElementDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"position", :struct, BungieNetAPI.Model.Object, options)
  end
end

