# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneContentItemCategory do
  @moduledoc """
  Part of our dynamic, localized Milestone content is arbitrary categories of items. These are built in our content management system, and thus aren&#39;t the same as programmatically generated rewards.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"title",
    :"itemHashes"
  ]

  @type t :: %__MODULE__{
    :"title" => String.t,
    :"itemHashes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyMilestoneContentItemCategory do
  def decode(value, _options) do
    value
  end
end

