# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyItemComponentSetOfint32 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"instances",
    :"objectives",
    :"perks",
    :"renderData",
    :"stats",
    :"sockets",
    :"talentGrids",
    :"plugStates"
  ]

  @type t :: %__MODULE__{
    :"instances" => DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent,
    :"objectives" => DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent,
    :"perks" => DictionaryComponentResponseOfint32AndDestinyItemPerksComponent,
    :"renderData" => DictionaryComponentResponseOfint32AndDestinyItemRenderComponent,
    :"stats" => DictionaryComponentResponseOfint32AndDestinyItemStatsComponent,
    :"sockets" => DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent,
    :"talentGrids" => DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent,
    :"plugStates" => DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyItemComponentSetOfint32 do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"instances", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent, options)
    |> deserialize(:"objectives", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent, options)
    |> deserialize(:"perks", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemPerksComponent, options)
    |> deserialize(:"renderData", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemRenderComponent, options)
    |> deserialize(:"stats", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemStatsComponent, options)
    |> deserialize(:"sockets", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent, options)
    |> deserialize(:"talentGrids", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent, options)
    |> deserialize(:"plugStates", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent, options)
  end
end

