# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyChallengesDestinyChallengeStatus do
  @moduledoc """
  Represents the status and other related information for a challenge that is - or was - available to a player.   A challenge is a bonus objective, generally tacked onto Quests or Activities, that provide additional variations on play.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"objective"
  ]

  @type t :: %__MODULE__{
    :"objective" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyChallengesDestinyChallengeStatus do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"objective", :struct, BungieNetAPI.Model.Object, options)
  end
end

