# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemStatsComponent do
  @moduledoc """
  If you want the stats on an item&#39;s instanced data, get this component.  These are stats like Attack, Defense etc... and *not* historical stats.  Note that some stats have additional computation in-game at runtime - for instance, Magazine Size - and thus these stats might not be 100% accurate compared to what you see in-game for some stats. I know, it sucks. I hate it too.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"stats"
  ]

  @type t :: %__MODULE__{
    :"stats" => %{optional(String.t) => DestinyDestinyStat}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemStatsComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"stats", :map, BungieNetAPI.Model.DestinyDestinyStat, options)
  end
end

