# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyActivityPlaylistItemDefinition do
  @moduledoc """
  If the activity is a playlist, this is the definition for a specific entry in the playlist: a single possible combination of Activity and Activity Mode that can be chosen.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"activityHash",
    :"directActivityModeHash",
    :"directActivityModeType",
    :"activityModeHashes",
    :"activityModeTypes"
  ]

  @type t :: %__MODULE__{
    :"activityHash" => integer(),
    :"directActivityModeHash" => integer(),
    :"directActivityModeType" => integer(),
    :"activityModeHashes" => [integer()],
    :"activityModeTypes" => [DestinyHistoricalStatsDefinitionsDestinyActivityModeType]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyActivityPlaylistItemDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"activityModeTypes", :list, BungieNetAPI.Model.DestinyHistoricalStatsDefinitionsDestinyActivityModeType, options)
  end
end

