# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyPlugUiStyles do
  @moduledoc """
  If the plug has a specific custom style, this enumeration will represent that style/those styles.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyPlugUiStyles do
  def decode(value, _options) do
    value
  end
end

