# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorRequirementDisplayEntryDefinition do
  @moduledoc """
  The localized properties of the requirementsDisplay, allowing information about the requirement or item being featured to be seen.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"icon",
    :"name",
    :"source",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"icon" => String.t,
    :"name" => String.t,
    :"source" => String.t,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorRequirementDisplayEntryDefinition do
  def decode(value, _options) do
    value
  end
end

