# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsItemsDestinyDerivedItemCategoryDefinition do
  @moduledoc """
  A shortcut for the fact that some items have a \&quot;Preview Vendor\&quot; - See DestinyInventoryItemDefinition.preview.previewVendorHash - that is intended to be used to show what items you can get as a result of acquiring or using this item.  A common example of this in Destiny 1 was Eververse \&quot;Boxes,\&quot; which could have many possible items. This \&quot;Preview Vendor\&quot; is not a vendor you can actually see in the game, but it defines categories and sale items for all of the possible items you could get from the Box so that the game can show them to you. We summarize that info here so that you don&#39;t have to do that Vendor lookup and aggregation manually.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categoryDescription",
    :"items"
  ]

  @type t :: %__MODULE__{
    :"categoryDescription" => String.t,
    :"items" => [DestinyDefinitionsItemsDestinyDerivedItemDefinition]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsItemsDestinyDerivedItemCategoryDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"items", :list, BungieNetAPI.Model.DestinyDefinitionsItemsDestinyDerivedItemDefinition, options)
  end
end

