# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneChallenge do
  @moduledoc """
  A Milestone can have many Challenges. Challenges are just extra Objectives that provide a fun way to mix-up play and provide extra rewards.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"objectiveHash",
    :"activityHash"
  ]

  @type t :: %__MODULE__{
    :"objectiveHash" => integer(),
    :"activityHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneChallenge do
  def decode(value, _options) do
    value
  end
end

