# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDefinitionsDestinyStatsGroupType do
  @moduledoc """
  If the enum value is &gt; 100, it is a \&quot;special\&quot; group that cannot be queried for directly (special cases apply to when they are returned, and are not relevant in general cases)
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDefinitionsDestinyStatsGroupType do
  def decode(value, _options) do
    value
  end
end

