# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyResponsesDestinyVendorsResponse do
  @moduledoc """
  A response containing all of the components for all requested vendors.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendors",
    :"categories",
    :"sales",
    :"itemComponents"
  ]

  @type t :: %__MODULE__{
    :"vendors" => Object,
    :"categories" => Object,
    :"sales" => Object,
    :"itemComponents" => %{optional(String.t) => DestinyItemComponentSetOfint32}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyResponsesDestinyVendorsResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"vendors", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"categories", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"sales", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"itemComponents", :map, BungieNetAPI.Model.DestinyItemComponentSetOfint32, options)
  end
end

