# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyComponentsItemsDestinyItemPlugComponent do
  @moduledoc """
  Plugs are non-instanced items that can provide Stat and Perk benefits when socketed into an instanced item. Items have Sockets, and Plugs are inserted into Sockets.  This component finds all items that are considered \&quot;Plugs\&quot; in your inventory, and return information about the plug aside from any specific Socket into which it could be inserted.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"plugItemHash",
    :"plugObjectives",
    :"canInsert",
    :"enabled",
    :"insertFailIndexes",
    :"enableFailIndexes"
  ]

  @type t :: %__MODULE__{
    :"plugItemHash" => integer(),
    :"plugObjectives" => [DestinyQuestsDestinyObjectiveProgress],
    :"canInsert" => boolean(),
    :"enabled" => boolean(),
    :"insertFailIndexes" => [integer()],
    :"enableFailIndexes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyComponentsItemsDestinyItemPlugComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plugObjectives", :list, BungieNetAPI.Model.DestinyQuestsDestinyObjectiveProgress, options)
  end
end

