# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition do
  @moduledoc """
  Many Destiny*Definition contracts - the \&quot;first order\&quot; entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"name",
    :"icon",
    :"hasIcon"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t,
    :"name" => String.t,
    :"icon" => String.t,
    :"hasIcon" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition do
  def decode(value, _options) do
    value
  end
end

