# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyTalentNodeDefinition do
  @moduledoc """
  Talent Grids on items have Nodes. These nodes have positions in the talent grid&#39;s UI, and contain \&quot;Steps\&quot; (DestinyTalentNodeStepDefinition), one of whom will be the \&quot;Current\&quot; step.  The Current Step determines the visual properties of the node, as well as what the node grants when it is activated.  See DestinyTalentGridDefinition for a more complete overview of how Talent Grids work, and how they are used in Destiny 2 (and how they were used in Destiny 1).
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nodeIndex",
    :"nodeHash",
    :"row",
    :"column",
    :"prerequisiteNodeIndexes",
    :"binaryPairNodeIndex",
    :"autoUnlocks",
    :"lastStepRepeats",
    :"isRandom",
    :"randomActivationRequirement",
    :"isRandomRepurchasable",
    :"steps",
    :"exclusiveWithNodeHashes",
    :"randomStartProgressionBarAtProgression",
    :"layoutIdentifier",
    :"groupHash",
    :"loreHash",
    :"nodeStyleIdentifier",
    :"ignoreForCompletion"
  ]

  @type t :: %__MODULE__{
    :"nodeIndex" => integer(),
    :"nodeHash" => integer(),
    :"row" => integer(),
    :"column" => integer(),
    :"prerequisiteNodeIndexes" => [integer()],
    :"binaryPairNodeIndex" => integer(),
    :"autoUnlocks" => boolean(),
    :"lastStepRepeats" => boolean(),
    :"isRandom" => boolean(),
    :"randomActivationRequirement" => Object,
    :"isRandomRepurchasable" => boolean(),
    :"steps" => [DestinyDefinitionsDestinyNodeStepDefinition],
    :"exclusiveWithNodeHashes" => [integer()],
    :"randomStartProgressionBarAtProgression" => integer(),
    :"layoutIdentifier" => String.t,
    :"groupHash" => integer(),
    :"loreHash" => integer(),
    :"nodeStyleIdentifier" => String.t,
    :"ignoreForCompletion" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyTalentNodeDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"randomActivationRequirement", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"steps", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyNodeStepDefinition, options)
  end
end

