# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyActivityGraphListEntryDefinition do
  @moduledoc """
  Destinations and Activities may have default Activity Graphs that should be shown when you bring up the Director and are playing in either.  This contract defines the graph referred to and the gating for when it is relevant.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"activityGraphHash"
  ]

  @type t :: %__MODULE__{
    :"activityGraphHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyActivityGraphListEntryDefinition do
  def decode(value, _options) do
    value
  end
end

