# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsItemsDestinyDerivedItemDefinition do
  @moduledoc """
  This is a reference to, and summary data for, a specific item that you can get as a result of Using or Acquiring some other Item (For example, this could be summary information for an Emote that you can get by opening an an Eververse Box) See DestinyDerivedItemCategoryDefinition for more information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemHash",
    :"itemName",
    :"itemDetail",
    :"itemDescription",
    :"iconPath",
    :"vendorItemIndex"
  ]

  @type t :: %__MODULE__{
    :"itemHash" => integer(),
    :"itemName" => String.t,
    :"itemDetail" => String.t,
    :"itemDescription" => String.t,
    :"iconPath" => String.t,
    :"vendorItemIndex" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsItemsDestinyDerivedItemDefinition do
  def decode(value, _options) do
    value
  end
end

