# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemInventoryBlockDefinition do
  @moduledoc """
  If the item can exist in an inventory - the overwhelming majority of them can and do - then this is the basic properties regarding the item&#39;s relationship with the inventory.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"stackUniqueLabel",
    :"maxStackSize",
    :"bucketTypeHash",
    :"recoveryBucketTypeHash",
    :"tierTypeHash",
    :"isInstanceItem",
    :"tierTypeName",
    :"tierType"
  ]

  @type t :: %__MODULE__{
    :"stackUniqueLabel" => String.t,
    :"maxStackSize" => integer(),
    :"bucketTypeHash" => integer(),
    :"recoveryBucketTypeHash" => integer(),
    :"tierTypeHash" => integer(),
    :"isInstanceItem" => boolean(),
    :"tierTypeName" => String.t,
    :"tierType" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemInventoryBlockDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"tierType", :struct, BungieNetAPI.Model.Object, options)
  end
end

