# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestone do
  @moduledoc """
  Information about milestones, presented in a character state-agnostic manner. Combine this data with DestinyMilestoneDefinition to get a full picture of the milestone, which is basically a checklist of things to do in the game. Think of this as GetPublicAdvisors 3.0, for those who used the Destiny 1 API.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"milestoneHash",
    :"availableQuests",
    :"vendorHashes",
    :"vendors",
    :"startDate",
    :"endDate"
  ]

  @type t :: %__MODULE__{
    :"milestoneHash" => integer(),
    :"availableQuests" => [DestinyMilestonesDestinyPublicMilestoneQuest],
    :"vendorHashes" => [integer()],
    :"vendors" => [DestinyMilestonesDestinyPublicMilestoneVendor],
    :"startDate" => DateTime.t,
    :"endDate" => DateTime.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestone do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"availableQuests", :list, BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneQuest, options)
    |> deserialize(:"vendors", :list, BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneVendor, options)
  end
end

