# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyNodeActivationRequirement do
  @moduledoc """
  Talent nodes have requirements that must be met before they can be activated.  This describes the material costs, the Level of the Talent Grid&#39;s progression required, and other conditional information that limits whether a talent node can be activated.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"gridLevel",
    :"materialRequirementHashes"
  ]

  @type t :: %__MODULE__{
    :"gridLevel" => integer(),
    :"materialRequirementHashes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyNodeActivationRequirement do
  def decode(value, _options) do
    value
  end
end

