# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemTranslationBlockDefinition do
  @moduledoc """
  This Block defines the rendering data associated with the item, if any.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"weaponPatternIdentifier",
    :"weaponPatternHash",
    :"defaultDyes",
    :"lockedDyes",
    :"customDyes",
    :"arrangements",
    :"hasGeometry"
  ]

  @type t :: %__MODULE__{
    :"weaponPatternIdentifier" => String.t,
    :"weaponPatternHash" => integer(),
    :"defaultDyes" => [DestinyDyeReference],
    :"lockedDyes" => [DestinyDyeReference],
    :"customDyes" => [DestinyDyeReference],
    :"arrangements" => [DestinyDefinitionsDestinyGearArtArrangementReference],
    :"hasGeometry" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemTranslationBlockDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"defaultDyes", :list, BungieNetAPI.Model.DestinyDyeReference, options)
    |> deserialize(:"lockedDyes", :list, BungieNetAPI.Model.DestinyDyeReference, options)
    |> deserialize(:"customDyes", :list, BungieNetAPI.Model.DestinyDyeReference, options)
    |> deserialize(:"arrangements", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyGearArtArrangementReference, options)
  end
end

