# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionSackEntryDefinition do
  @moduledoc """
  Compare this sackType to the sack identifier in the DestinyInventoryItemDefinition.vendorSackType property of items. If they match, show this sack with this interaction.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sackType"
  ]

  @type t :: %__MODULE__{
    :"sackType" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionSackEntryDefinition do
  def decode(value, _options) do
    value
  end
end

