# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneQuest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"questItemHash",
    :"activity",
    :"challenges"
  ]

  @type t :: %__MODULE__{
    :"questItemHash" => integer(),
    :"activity" => Object,
    :"challenges" => [DestinyMilestonesDestinyPublicMilestoneChallenge]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneQuest do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"activity", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"challenges", :list, BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneChallenge, options)
  end
end

