# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyDamageTypeDefinition do
  @moduledoc """
  All damage types that are possible in the game are defined here, along with localized info and icons as needed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayProperties",
    :"transparentIconPath",
    :"showIcon",
    :"enumValue",
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"displayProperties" => Object,
    :"transparentIconPath" => String.t,
    :"showIcon" => boolean(),
    :"enumValue" => Object,
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyDamageTypeDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"enumValue", :struct, BungieNetAPI.Model.Object, options)
  end
end

