# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalStatsValuePair do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"displayValue"
  ]

  @type t :: %__MODULE__{
    :"value" => float(),
    :"displayValue" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalStatsValuePair do
  def decode(value, _options) do
    value
  end
end

