# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyLocationReleaseDefinition do
  @moduledoc """
  A specific \&quot;spot\&quot; referred to by a location. Only one of these can be active at a time for a given Location.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayProperties",
    :"spawnPoint",
    :"destinationHash",
    :"activityHash",
    :"activityGraphHash",
    :"activityGraphNodeHash",
    :"activityBubbleName",
    :"activityPathBundle",
    :"activityPathDestination",
    :"navPointType",
    :"worldPosition"
  ]

  @type t :: %__MODULE__{
    :"displayProperties" => Object,
    :"spawnPoint" => integer(),
    :"destinationHash" => integer(),
    :"activityHash" => integer(),
    :"activityGraphHash" => integer(),
    :"activityGraphNodeHash" => integer(),
    :"activityBubbleName" => integer(),
    :"activityPathBundle" => integer(),
    :"activityPathDestination" => integer(),
    :"navPointType" => Object,
    :"worldPosition" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyLocationReleaseDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"navPointType", :struct, BungieNetAPI.Model.Object, options)
  end
end

