# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyActivityModeDefinition do
  @moduledoc """
  This definition represents an \&quot;Activity Mode\&quot; as it exists in the Historical Stats endpoints. An individual Activity Mode represents a collection of activities that are played in a certain way. For example, Nightfall Strikes are part of a \&quot;Nightfall\&quot; activity mode, and any activities played as the PVP mode \&quot;Clash\&quot; are part of the \&quot;Clash activity mode.  Activity modes are nested under each other in a hierarchy, so that if you ask for - for example - \&quot;AllPvP\&quot;, you will get any PVP activities that the user has played, regardless of what specific PVP mode was being played.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayProperties",
    :"pgcrImage",
    :"modeType",
    :"activityModeCategory",
    :"isTeamBased",
    :"isAggregateMode",
    :"parentHashes",
    :"friendlyName",
    :"activityModeMappings",
    :"display",
    :"order",
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"displayProperties" => DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition,
    :"pgcrImage" => String.t,
    :"modeType" => Object,
    :"activityModeCategory" => Object,
    :"isTeamBased" => boolean(),
    :"isAggregateMode" => boolean(),
    :"parentHashes" => [integer()],
    :"friendlyName" => String.t,
    :"activityModeMappings" => %{optional(String.t) => DestinyHistoricalStatsDefinitionsDestinyActivityModeType},
    :"display" => boolean(),
    :"order" => integer(),
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyActivityModeDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition, options)
    |> deserialize(:"modeType", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"activityModeCategory", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"activityModeMappings", :map, BungieNetAPI.Model.DestinyHistoricalStatsDefinitionsDestinyActivityModeType, options)
  end
end

