# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemActionRequiredItemDefinition do
  @moduledoc """
  The definition of an item and quantity required in a character&#39;s inventory in order to perform an action.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"count",
    :"itemHash",
    :"deleteOnAction"
  ]

  @type t :: %__MODULE__{
    :"count" => integer(),
    :"itemHash" => integer(),
    :"deleteOnAction" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemActionRequiredItemDefinition do
  def decode(value, _options) do
    value
  end
end

