# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemSourceBlockDefinition do
  @moduledoc """
  Data about an item&#39;s \&quot;sources\&quot;: ways that the item can be obtained.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sourceHashes",
    :"sources",
    :"exclusive"
  ]

  @type t :: %__MODULE__{
    :"sourceHashes" => [integer()],
    :"sources" => [DestinyDefinitionsSourcesDestinyItemSourceDefinition],
    :"exclusive" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemSourceBlockDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sources", :list, BungieNetAPI.Model.DestinyDefinitionsSourcesDestinyItemSourceDefinition, options)
    |> deserialize(:"exclusive", :struct, BungieNetAPI.Model.Object, options)
  end
end

