# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyResponsesDestinyProfileResponse do
  @moduledoc """
  The response for GetDestinyProfile, with components for character and item-level data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendorReceipts",
    :"profileInventory",
    :"profileCurrencies",
    :"profile",
    :"profileKiosks",
    :"characters",
    :"characterInventories",
    :"characterProgressions",
    :"characterRenderData",
    :"characterActivities",
    :"characterEquipment",
    :"characterKiosks",
    :"itemComponents"
  ]

  @type t :: %__MODULE__{
    :"vendorReceipts" => Object,
    :"profileInventory" => Object,
    :"profileCurrencies" => Object,
    :"profile" => Object,
    :"profileKiosks" => Object,
    :"characters" => Object,
    :"characterInventories" => Object,
    :"characterProgressions" => Object,
    :"characterRenderData" => Object,
    :"characterActivities" => Object,
    :"characterEquipment" => Object,
    :"characterKiosks" => Object,
    :"itemComponents" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyResponsesDestinyProfileResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"vendorReceipts", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"profileInventory", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"profileCurrencies", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"profile", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"profileKiosks", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characters", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characterInventories", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characterProgressions", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characterRenderData", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characterActivities", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characterEquipment", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"characterKiosks", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"itemComponents", :struct, BungieNetAPI.Model.Object, options)
  end
end

