# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinySocketsDestinyItemPlug do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"plugItemHash",
    :"plugObjectives",
    :"canInsert",
    :"enabled",
    :"insertFailIndexes",
    :"enableFailIndexes"
  ]

  @type t :: %__MODULE__{
    :"plugItemHash" => integer(),
    :"plugObjectives" => [DestinyQuestsDestinyObjectiveProgress],
    :"canInsert" => boolean(),
    :"enabled" => boolean(),
    :"insertFailIndexes" => [integer()],
    :"enableFailIndexes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinySocketsDestinyItemPlug do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plugObjectives", :list, BungieNetAPI.Model.DestinyQuestsDestinyObjectiveProgress, options)
  end
end

