# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyCharacterDestinyCharacterPeerView do
  @moduledoc """
  A minimal view of a character&#39;s equipped items, for the purpose of rendering a summary screen or showing the character in 3D.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"equipment"
  ]

  @type t :: %__MODULE__{
    :"equipment" => [DestinyCharacterDestinyItemPeerView]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyCharacterDestinyCharacterPeerView do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"equipment", :list, BungieNetAPI.Model.DestinyCharacterDestinyItemPeerView, options)
  end
end

