# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorSaleItemComponent do
  @moduledoc """
  Request this component if you want the details about an item being sold in relation to the character making the request: whether the character can buy it, whether they can afford it, and other data related to purchasing the item.  Note that if you want instance, stats, etc... data for the item, you&#39;ll have to request additional components such as ItemInstances, ItemPerks etc... and acquire them from the DestinyVendorResponse&#39;s \&quot;items\&quot; property.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendorItemIndex",
    :"itemHash",
    :"quantity",
    :"saleStatus",
    :"costs",
    :"requiredUnlocks",
    :"unlockStatuses",
    :"failureIndexes"
  ]

  @type t :: %__MODULE__{
    :"vendorItemIndex" => integer(),
    :"itemHash" => integer(),
    :"quantity" => integer(),
    :"saleStatus" => Object,
    :"costs" => [DestinyDestinyItemQuantity],
    :"requiredUnlocks" => [integer()],
    :"unlockStatuses" => [DestinyDestinyUnlockStatus],
    :"failureIndexes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorSaleItemComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"saleStatus", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"costs", :list, BungieNetAPI.Model.DestinyDestinyItemQuantity, options)
    |> deserialize(:"unlockStatuses", :list, BungieNetAPI.Model.DestinyDestinyUnlockStatus, options)
  end
end

