# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorItemDefinition do
  @moduledoc """
  This represents an item being sold by the vendor.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendorItemIndex",
    :"itemHash",
    :"quantity",
    :"failureIndexes",
    :"currencies",
    :"refundPolicy",
    :"refundTimeLimit",
    :"creationLevels",
    :"displayCategoryIndex",
    :"categoryIndex",
    :"originalCategoryIndex",
    :"minimumLevel",
    :"maximumLevel",
    :"action",
    :"displayCategory",
    :"inventoryBucketHash",
    :"visibilityScope",
    :"purchasableScope",
    :"exclusivity",
    :"isOffer",
    :"isCrm"
  ]

  @type t :: %__MODULE__{
    :"vendorItemIndex" => integer(),
    :"itemHash" => integer(),
    :"quantity" => integer(),
    :"failureIndexes" => [integer()],
    :"currencies" => [DestinyDestinyItemQuantity],
    :"refundPolicy" => Object,
    :"refundTimeLimit" => integer(),
    :"creationLevels" => [DestinyDefinitionsDestinyItemCreationEntryLevelDefinition],
    :"displayCategoryIndex" => integer(),
    :"categoryIndex" => integer(),
    :"originalCategoryIndex" => integer(),
    :"minimumLevel" => integer(),
    :"maximumLevel" => integer(),
    :"action" => Object,
    :"displayCategory" => String.t,
    :"inventoryBucketHash" => integer(),
    :"visibilityScope" => Object,
    :"purchasableScope" => Object,
    :"exclusivity" => Object,
    :"isOffer" => boolean(),
    :"isCrm" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorItemDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"currencies", :list, BungieNetAPI.Model.DestinyDestinyItemQuantity, options)
    |> deserialize(:"refundPolicy", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"creationLevels", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyItemCreationEntryLevelDefinition, options)
    |> deserialize(:"action", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"visibilityScope", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"purchasableScope", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"exclusivity", :struct, BungieNetAPI.Model.Object, options)
  end
end

