# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorCategoriesComponent do
  @moduledoc """
  A vendor can have many categories of items that they sell. This component will return the category information for available items, as well as the index into those items in the user&#39;s sale item list.  Note that, since both the category and items are indexes, this data is Content Version dependent. Be sure to check that your content is up to date before using this data. This is an unfortunate, but permanent, limitation of Vendor data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categories"
  ]

  @type t :: %__MODULE__{
    :"categories" => [DestinyEntitiesVendorsDestinyVendorCategory]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorCategoriesComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"categories", :list, BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorCategory, options)
  end
end

