# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDestinyTalentNodeStatBlock do
  @moduledoc """
  This property has some history. A talent grid can provide stats on both the item it&#39;s related to and the character equipping the item. This returns data about those stat bonuses.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"currentStepStats",
    :"nextStepStats"
  ]

  @type t :: %__MODULE__{
    :"currentStepStats" => [DestinyDestinyStat],
    :"nextStepStats" => [DestinyDestinyStat]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDestinyTalentNodeStatBlock do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"currentStepStats", :list, BungieNetAPI.Model.DestinyDestinyStat, options)
    |> deserialize(:"nextStepStats", :list, BungieNetAPI.Model.DestinyDestinyStat, options)
  end
end

