# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDestinyStat do
  @moduledoc """
  Represents a stat on an item *or* Character (NOT a Historical Stat, but a physical attribute stat like Attack, Defense etc...)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"statHash",
    :"value",
    :"maximumValue"
  ]

  @type t :: %__MODULE__{
    :"statHash" => integer(),
    :"value" => integer(),
    :"maximumValue" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDestinyStat do
  def decode(value, _options) do
    value
  end
end

