# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemActionBlockDefinition do
  @moduledoc """
  If an item can have an action performed on it (like \&quot;Dismantle\&quot;), it will be defined here if you care.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"verbName",
    :"verbDescription",
    :"isPositive",
    :"overlayScreenName",
    :"overlayIcon",
    :"requiredCooldownSeconds",
    :"requiredItems",
    :"progressionRewards",
    :"actionTypeLabel",
    :"requiredLocation",
    :"requiredCooldownHash",
    :"deleteOnAction",
    :"consumeEntireStack",
    :"useOnAcquire"
  ]

  @type t :: %__MODULE__{
    :"verbName" => String.t,
    :"verbDescription" => String.t,
    :"isPositive" => boolean(),
    :"overlayScreenName" => String.t,
    :"overlayIcon" => String.t,
    :"requiredCooldownSeconds" => integer(),
    :"requiredItems" => [DestinyDefinitionsDestinyItemActionRequiredItemDefinition],
    :"progressionRewards" => [DestinyDefinitionsDestinyProgressionRewardDefinition],
    :"actionTypeLabel" => String.t,
    :"requiredLocation" => String.t,
    :"requiredCooldownHash" => integer(),
    :"deleteOnAction" => boolean(),
    :"consumeEntireStack" => boolean(),
    :"useOnAcquire" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemActionBlockDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"requiredItems", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyItemActionRequiredItemDefinition, options)
    |> deserialize(:"progressionRewards", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyProgressionRewardDefinition, options)
  end
end

