# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDestinyVendorInteractionRewardSelection do
  @moduledoc """
  When a Vendor Interaction provides rewards, they&#39;ll either let you choose one or let you have all of them. This determines which it will be.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDestinyVendorInteractionRewardSelection do
  def decode(value, _options) do
    value
  end
end

