# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyReportingRequestsDestinyReportOffensePgcrRequest do
  @moduledoc """
  If you want to report a player causing trouble in a game, this request will let you report that player and the specific PGCR in which the trouble was caused, along with why.  Please don&#39;t do this just because you dislike the person! I mean, I know people will do it anyways, but can you like take a good walk, or put a curse on them or something? Do me a solid and reconsider.  Note that this request object doesn&#39;t have the actual PGCR ID nor your Account/Character ID in it. We will infer that information from your authentication information and the PGCR ID that you pass into the URL of the reporting endpoint itself.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reasonCategoryHashes",
    :"reasonHashes",
    :"offendingCharacterId"
  ]

  @type t :: %__MODULE__{
    :"reasonCategoryHashes" => [integer()],
    :"reasonHashes" => [integer()],
    :"offendingCharacterId" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyReportingRequestsDestinyReportOffensePgcrRequest do
  def decode(value, _options) do
    value
  end
end

