# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesProfilesDestinyVendorReceiptsComponent do
  @moduledoc """
  For now, this isn&#39;t used for much: it&#39;s a record of the recent refundable purchases that the user has made. In the future, it could be used for providing refunds/buyback via the API. Wouldn&#39;t that be fun?
  """

  @derive [Poison.Encoder]
  defstruct [
    :"receipts"
  ]

  @type t :: %__MODULE__{
    :"receipts" => [DestinyVendorsDestinyVendorReceipt]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesProfilesDestinyVendorReceiptsComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"receipts", :list, BungieNetAPI.Model.DestinyVendorsDestinyVendorReceipt, options)
  end
end

