# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesCharactersDestinyCharacterProgressionComponent do
  @moduledoc """
  This component returns anything that could be considered \&quot;Progression\&quot; on a user: data where the user is gaining levels, reputation, completions, rewards, etc...
  """

  @derive [Poison.Encoder]
  defstruct [
    :"progressions",
    :"factions",
    :"milestones",
    :"quests",
    :"uninstancedItemObjectives"
  ]

  @type t :: %__MODULE__{
    :"progressions" => %{optional(String.t) => DestinyDestinyProgression},
    :"factions" => %{optional(String.t) => DestinyProgressionDestinyFactionProgression},
    :"milestones" => %{optional(String.t) => DestinyMilestonesDestinyMilestone},
    :"quests" => [DestinyQuestsDestinyQuestStatus],
    :"uninstancedItemObjectives" => %{optional(String.t) => [DestinyQuestsDestinyObjectiveProgress]}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesCharactersDestinyCharacterProgressionComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"progressions", :map, BungieNetAPI.Model.DestinyDestinyProgression, options)
    |> deserialize(:"factions", :map, BungieNetAPI.Model.DestinyProgressionDestinyFactionProgression, options)
    |> deserialize(:"milestones", :map, BungieNetAPI.Model.DestinyMilestonesDestinyMilestone, options)
    |> deserialize(:"quests", :list, BungieNetAPI.Model.DestinyQuestsDestinyQuestStatus, options)
  end
end

