# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemQualityBlockDefinition do
  @moduledoc """
  An item&#39;s \&quot;Quality\&quot; determines its calculated stats. The Level at which the item spawns is combined with its \&quot;qualityLevel\&quot; along with some additional calculations to determine the value of those stats.  In Destiny 2, most items don&#39;t have default item levels and quality, making this property less useful: these apparently are almost always determined by the complex mechanisms of the Reward system rather than statically. They are still provided here in case they are still useful for people. This also contains some information about Infusion.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemLevels",
    :"qualityLevel",
    :"infusionCategoryName",
    :"infusionCategoryHash",
    :"infusionCategoryHashes",
    :"progressionLevelRequirementHash"
  ]

  @type t :: %__MODULE__{
    :"itemLevels" => [integer()],
    :"qualityLevel" => integer(),
    :"infusionCategoryName" => String.t,
    :"infusionCategoryHash" => integer(),
    :"infusionCategoryHashes" => [integer()],
    :"progressionLevelRequirementHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemQualityBlockDefinition do
  def decode(value, _options) do
    value
  end
end

