# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyConfigDestinyManifest do
  @moduledoc """
  DestinyManifest is the external-facing contract for just the properties needed by those calling the Destiny Platform.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"version",
    :"mobileAssetContentPath",
    :"mobileGearAssetDataBases",
    :"mobileWorldContentPaths",
    :"mobileClanBannerDatabasePath",
    :"mobileGearCDN"
  ]

  @type t :: %__MODULE__{
    :"version" => String.t,
    :"mobileAssetContentPath" => String.t,
    :"mobileGearAssetDataBases" => [DestinyConfigGearAssetDataBaseDefinition],
    :"mobileWorldContentPaths" => %{optional(String.t) => String.t},
    :"mobileClanBannerDatabasePath" => String.t,
    :"mobileGearCDN" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyConfigDestinyManifest do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mobileGearAssetDataBases", :list, BungieNetAPI.Model.DestinyConfigGearAssetDataBaseDefinition, options)
  end
end

