# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyItemComponentSetOfint64 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"instances",
    :"objectives",
    :"perks",
    :"renderData",
    :"stats",
    :"sockets",
    :"talentGrids",
    :"plugStates"
  ]

  @type t :: %__MODULE__{
    :"instances" => DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent,
    :"objectives" => DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent,
    :"perks" => DictionaryComponentResponseOfint64AndDestinyItemPerksComponent,
    :"renderData" => DictionaryComponentResponseOfint64AndDestinyItemRenderComponent,
    :"stats" => DictionaryComponentResponseOfint64AndDestinyItemStatsComponent,
    :"sockets" => DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent,
    :"talentGrids" => DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent,
    :"plugStates" => DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyItemComponentSetOfint64 do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"instances", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent, options)
    |> deserialize(:"objectives", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent, options)
    |> deserialize(:"perks", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemPerksComponent, options)
    |> deserialize(:"renderData", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemRenderComponent, options)
    |> deserialize(:"stats", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemStatsComponent, options)
    |> deserialize(:"sockets", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent, options)
    |> deserialize(:"talentGrids", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent, options)
    |> deserialize(:"plugStates", :struct, BungieNetAPI.Model.DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent, options)
  end
end

