# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemComponent do
  @moduledoc """
  The base item component, filled with properties that are generally useful to know in any item request or that don&#39;t feel worthwhile to put in their own component.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemHash",
    :"itemInstanceId",
    :"quantity",
    :"bindStatus",
    :"location",
    :"bucketHash",
    :"transferStatus",
    :"lockable",
    :"state"
  ]

  @type t :: %__MODULE__{
    :"itemHash" => integer(),
    :"itemInstanceId" => integer(),
    :"quantity" => integer(),
    :"bindStatus" => Object,
    :"location" => Object,
    :"bucketHash" => integer(),
    :"transferStatus" => Object,
    :"lockable" => boolean(),
    :"state" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bindStatus", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"location", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"transferStatus", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"state", :struct, BungieNetAPI.Model.Object, options)
  end
end

