# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeFeaturingStateDefinition do
  @moduledoc """
  Nodes can have different visual states. This object represents a single visual state (\&quot;highlight type\&quot;) that a node can be in, and the unlock expression condition to determine whether it should be set.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"highlightType"
  ]

  @type t :: %__MODULE__{
    :"highlightType" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeFeaturingStateDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"highlightType", :struct, BungieNetAPI.Model.Object, options)
  end
end

