# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition do
  @moduledoc """
  Defines a plug \&quot;Category\&quot; that is allowed to be plugged into a socket of this type.  This should be compared against a given plug item&#39;s DestinyInventoryItemDefinition.plug.plugCategoryHash, which indicates the plug item&#39;s category.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categoryHash",
    :"categoryIdentifier",
    :"reinitializationPossiblePlugHashes"
  ]

  @type t :: %__MODULE__{
    :"categoryHash" => integer(),
    :"categoryIdentifier" => String.t,
    :"reinitializationPossiblePlugHashes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsSocketsDestinyPlugWhitelistEntryDefinition do
  def decode(value, _options) do
    value
  end
end

