# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesCharactersDestinyCharacterActivitiesComponent do
  @moduledoc """
  This component holds activity data for a character. It will tell you about the character&#39;s current activity status, as well as activities that are available to the user.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"dateActivityStarted",
    :"availableActivities",
    :"currentActivityHash",
    :"currentActivityModeHash",
    :"currentActivityModeType",
    :"currentActivityModeHashes",
    :"currentActivityModeTypes",
    :"currentPlaylistActivityHash",
    :"lastCompletedStoryHash"
  ]

  @type t :: %__MODULE__{
    :"dateActivityStarted" => DateTime.t,
    :"availableActivities" => [DestinyDestinyActivity],
    :"currentActivityHash" => integer(),
    :"currentActivityModeHash" => integer(),
    :"currentActivityModeType" => integer(),
    :"currentActivityModeHashes" => [integer()],
    :"currentActivityModeTypes" => [DestinyHistoricalStatsDefinitionsDestinyActivityModeType],
    :"currentPlaylistActivityHash" => integer(),
    :"lastCompletedStoryHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesCharactersDestinyCharacterActivitiesComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"availableActivities", :list, BungieNetAPI.Model.DestinyDestinyActivity, options)
    |> deserialize(:"currentActivityModeTypes", :list, BungieNetAPI.Model.DestinyHistoricalStatsDefinitionsDestinyActivityModeType, options)
  end
end

