# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardsDefinition do
  @moduledoc """
  If rewards are given in a quest - as opposed to overall in the entire Milestone - there&#39;s way less to track. We&#39;re going to simplify this contract as a result. However, this also gives us the opportunity to potentially put more than just item information into the reward data if we&#39;re able to mine it out in the future. Remember this if you come back and ask \&quot;why are quest reward items nested inside of their own class?\&quot;
  """

  @derive [Poison.Encoder]
  defstruct [
    :"items"
  ]

  @type t :: %__MODULE__{
    :"items" => [DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardsDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"items", :list, BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem, options)
  end
end

