# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneActivityDefinition do
  @moduledoc """
  Milestones can have associated activities which provide additional information about the context, challenges, modifiers, state etc... related to this Milestone.   Information we need to be able to return that data is defined here, along with Tier data to establish a relationship between a conceptual Activity and its difficulty levels and variants.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"conceptualActivityHash",
    :"variants"
  ]

  @type t :: %__MODULE__{
    :"conceptualActivityHash" => integer(),
    :"variants" => %{optional(String.t) => DestinyDefinitionsMilestonesDestinyMilestoneActivityVariantDefinition}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneActivityDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"variants", :map, BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneActivityVariantDefinition, options)
  end
end

