# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyResponsesDestinyItemResponse do
  @moduledoc """
  The response object for retrieving an individual instanced item. None of these components are relevant for an item that doesn&#39;t have an \&quot;itemInstanceId\&quot;: for those, get your information from the DestinyInventoryDefinition.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"characterId",
    :"item",
    :"instance",
    :"objectives",
    :"perks",
    :"renderData",
    :"stats",
    :"talentGrid",
    :"sockets"
  ]

  @type t :: %__MODULE__{
    :"characterId" => integer(),
    :"item" => Object,
    :"instance" => Object,
    :"objectives" => Object,
    :"perks" => Object,
    :"renderData" => Object,
    :"stats" => Object,
    :"talentGrid" => Object,
    :"sockets" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyResponsesDestinyItemResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"item", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"instance", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"objectives", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"perks", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"renderData", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"stats", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"talentGrid", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"sockets", :struct, BungieNetAPI.Model.Object, options)
  end
end

