# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketEntryDefinition do
  @moduledoc """
  The definition information for a specific socket on an item. This will determine how the socket behaves in-game.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"socketTypeHash",
    :"singleInitialItemHash",
    :"reusablePlugItems",
    :"preventInitializationOnVendorPurchase",
    :"hidePerksInItemTooltip"
  ]

  @type t :: %__MODULE__{
    :"socketTypeHash" => integer(),
    :"singleInitialItemHash" => integer(),
    :"reusablePlugItems" => [DestinyDefinitionsDestinyItemSocketEntryPlugItemDefinition],
    :"preventInitializationOnVendorPurchase" => boolean(),
    :"hidePerksInItemTooltip" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketEntryDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"reusablePlugItems", :list, BungieNetAPI.Model.DestinyDefinitionsDestinyItemSocketEntryPlugItemDefinition, options)
  end
end

