# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyObjectiveStatEntryDefinition do
  @moduledoc """
  Defines the conditions under which stat modifications will be applied to a Character while participating in an objective.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"stat",
    :"style"
  ]

  @type t :: %__MODULE__{
    :"stat" => Object,
    :"style" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyObjectiveStatEntryDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"stat", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"style", :struct, BungieNetAPI.Model.Object, options)
  end
end

