# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalWeaponStatsData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"weapons"
  ]

  @type t :: %__MODULE__{
    :"weapons" => [DestinyHistoricalStatsDestinyHistoricalWeaponStats]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalWeaponStatsData do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"weapons", :list, BungieNetAPI.Model.DestinyHistoricalStatsDestinyHistoricalWeaponStats, options)
  end
end

