# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsItemsDestinyItemPlugDefinition do
  @moduledoc """
  If an item is a Plug, its DestinyInventoryItemDefinition.plug property will be populated with an instance of one of these bad boys.  This gives information about when it can be inserted, what the plug&#39;s category is (and thus whether it is compatible with a socket... see DestinySocketTypeDefinition for information about Plug Categories and socket compatibility), whether it is enabled and other Plug info.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"insertionRules",
    :"plugCategoryIdentifier",
    :"plugCategoryHash",
    :"onActionRecreateSelf",
    :"insertionMaterialRequirementHash",
    :"previewItemOverrideHash",
    :"enabledMaterialRequirementHash",
    :"enabledRules",
    :"uiPlugLabel",
    :"plugStyle",
    :"isPseudoPlug",
    :"plugAvailability"
  ]

  @type t :: %__MODULE__{
    :"insertionRules" => [DestinyDefinitionsItemsDestinyPlugRuleDefinition],
    :"plugCategoryIdentifier" => String.t,
    :"plugCategoryHash" => integer(),
    :"onActionRecreateSelf" => boolean(),
    :"insertionMaterialRequirementHash" => integer(),
    :"previewItemOverrideHash" => integer(),
    :"enabledMaterialRequirementHash" => integer(),
    :"enabledRules" => [DestinyDefinitionsItemsDestinyPlugRuleDefinition],
    :"uiPlugLabel" => String.t,
    :"plugStyle" => DestinyPlugUiStyles,
    :"isPseudoPlug" => boolean(),
    :"plugAvailability" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsItemsDestinyItemPlugDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"insertionRules", :list, BungieNetAPI.Model.DestinyDefinitionsItemsDestinyPlugRuleDefinition, options)
    |> deserialize(:"enabledRules", :list, BungieNetAPI.Model.DestinyDefinitionsItemsDestinyPlugRuleDefinition, options)
    |> deserialize(:"plugStyle", :struct, BungieNetAPI.Model.DestinyPlugUiStyles, options)
    |> deserialize(:"plugAvailability", :struct, BungieNetAPI.Model.Object, options)
  end
end

