# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneVendorDefinition do
  @moduledoc """
  If the Milestone or a component has vendors whose inventories could/should be displayed that are relevant to it, this will return the vendor in question.   It also contains information we need to determine whether that vendor is actually relevant at the moment, given the user&#39;s current state.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"vendorHash"
  ]

  @type t :: %__MODULE__{
    :"vendorHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneVendorDefinition do
  def decode(value, _options) do
    value
  end
end

