# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorActionDefinition do
  @moduledoc """
  If a vendor can ever end up performing actions, these are the properties that will be related to those actions. I&#39;m not going to bother documenting this yet, as it is unused and unclear if it will ever be used... but in case it is ever populated and someone finds it useful, it is defined here.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"executeSeconds",
    :"icon",
    :"name",
    :"verb",
    :"isPositive",
    :"actionId",
    :"actionHash",
    :"autoPerformAction"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t,
    :"executeSeconds" => integer(),
    :"icon" => String.t,
    :"name" => String.t,
    :"verb" => String.t,
    :"isPositive" => boolean(),
    :"actionId" => String.t,
    :"actionHash" => integer(),
    :"autoPerformAction" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorActionDefinition do
  def decode(value, _options) do
    value
  end
end

