# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneValueDefinition do
  @moduledoc """
  The definition for information related to a key/value pair that is relevant for a particular Milestone or component within the Milestone.   This lets us more flexibly pass up information that&#39;s useful to someone, even if it&#39;s not necessarily us.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"displayProperties"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"displayProperties" => DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneValueDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition, options)
  end
end

