# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyTalentNodeExclusiveSetDefinition do
  @moduledoc """
  The list of indexes into the Talent Grid&#39;s \&quot;nodes\&quot; property for nodes in this exclusive set. (See DestinyTalentNodeDefinition.nodeIndex)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nodeIndexes"
  ]

  @type t :: %__MODULE__{
    :"nodeIndexes" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyTalentNodeExclusiveSetDefinition do
  def decode(value, _options) do
    value
  end
end

