# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"baseQualityTransferRatio",
    :"minimumQualityIncrement"
  ]

  @type t :: %__MODULE__{
    :"baseQualityTransferRatio" => float(),
    :"minimumQualityIncrement" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock do
  def decode(value, _options) do
    value
  end
end

