# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDestinyLeaderboardEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rank",
    :"player",
    :"characterId",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"rank" => integer(),
    :"player" => Object,
    :"characterId" => integer(),
    :"value" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDestinyLeaderboardEntry do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"player", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"value", :struct, BungieNetAPI.Model.Object, options)
  end
end

