# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyEquippingBlockDefinition do
  @moduledoc """
  Items that can be equipped define this block. It contains information we need to understand how and when the item can be equipped.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"gearsetItemHash",
    :"uniqueLabel",
    :"uniqueLabelHash",
    :"equipmentSlotTypeHash",
    :"attributes",
    :"displayStrings"
  ]

  @type t :: %__MODULE__{
    :"gearsetItemHash" => integer(),
    :"uniqueLabel" => String.t,
    :"uniqueLabelHash" => integer(),
    :"equipmentSlotTypeHash" => integer(),
    :"attributes" => Object,
    :"displayStrings" => [String.t]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyEquippingBlockDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"attributes", :struct, BungieNetAPI.Model.Object, options)
  end
end

