# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneRewardEntryDefinition do
  @moduledoc """
  The definition of a specific reward, which may be contained in a category of rewards and that has optional information about how it is obtained.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"rewardEntryHash",
    :"rewardEntryIdentifier",
    :"items",
    :"vendorHash",
    :"displayProperties",
    :"order"
  ]

  @type t :: %__MODULE__{
    :"rewardEntryHash" => integer(),
    :"rewardEntryIdentifier" => String.t,
    :"items" => [DestinyDestinyItemQuantity],
    :"vendorHash" => integer(),
    :"displayProperties" => Object,
    :"order" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsMilestonesDestinyMilestoneRewardEntryDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"items", :list, BungieNetAPI.Model.DestinyDestinyItemQuantity, options)
    |> deserialize(:"displayProperties", :struct, BungieNetAPI.Model.Object, options)
  end
end

