# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeActivityDefinition do
  @moduledoc """
  The actual activity to be redirected to when you click on the node. Note that a node can have many Activities attached to it: but only one will be active at any given time. The list of Node Activities will be traversed, and the first one found to be active will be displayed. This way, a node can layer multiple variants of an activity on top of each other. For instance, one node can control the weekly Crucible Playlist. There are multiple possible playlists, but only one is active for the week.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nodeActivityId",
    :"activityHash"
  ]

  @type t :: %__MODULE__{
    :"nodeActivityId" => integer(),
    :"activityHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeActivityDefinition do
  def decode(value, _options) do
    value
  end
end

