# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionReplyDefinition do
  @moduledoc """
  When the interaction is replied to, Reward sites will fire and items potentially selected based on whether the given unlock expression is TRUE.  You can potentially choose one from multiple replies when replying to an interaction: this is how you get either/or rewards from vendors.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemRewardsSelection",
    :"reply",
    :"replyType"
  ]

  @type t :: %__MODULE__{
    :"itemRewardsSelection" => Object,
    :"reply" => String.t,
    :"replyType" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyVendorInteractionReplyDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"itemRewardsSelection", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"replyType", :struct, BungieNetAPI.Model.Object, options)
  end
end

