# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyComponentsVendorsDestinyVendorSaleItemSetComponent do
  @moduledoc """
  The collection of all items currently being sold by a specific Vendor and visible to the given character for which the request was made.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"saleItems"
  ]

  @type t :: %__MODULE__{
    :"saleItems" => %{optional(String.t) => DestinyEntitiesVendorsDestinyVendorSaleItemComponent}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyComponentsVendorsDestinyVendorSaleItemSetComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"saleItems", :map, BungieNetAPI.Model.DestinyEntitiesVendorsDestinyVendorSaleItemComponent, options)
  end
end

