# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDestinyProgression do
  @moduledoc """
  Information about a current character&#39;s status with a Progression. A progression is a value that can increase with activity and has levels. Think Character Level and Reputation Levels. Combine this \&quot;live\&quot; data with the related DestinyProgressionDefinition for a full picture of the Progression.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"progressionHash",
    :"dailyProgress",
    :"dailyLimit",
    :"weeklyProgress",
    :"weeklyLimit",
    :"currentProgress",
    :"level",
    :"levelCap",
    :"stepIndex",
    :"progressToNextLevel",
    :"nextLevelAt"
  ]

  @type t :: %__MODULE__{
    :"progressionHash" => integer(),
    :"dailyProgress" => integer(),
    :"dailyLimit" => integer(),
    :"weeklyProgress" => integer(),
    :"weeklyLimit" => integer(),
    :"currentProgress" => integer(),
    :"level" => integer(),
    :"levelCap" => integer(),
    :"stepIndex" => integer(),
    :"progressToNextLevel" => integer(),
    :"nextLevelAt" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDestinyProgression do
  def decode(value, _options) do
    value
  end
end

