# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyPerksDestinyPerkReference do
  @moduledoc """
  The list of perks to display in an item tooltip - and whether or not they have been activated.  Perks apply a variety of effects to a character, and are generally either intrinsic to the item or provided in activated talent nodes or sockets.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"perkHash",
    :"iconPath",
    :"isActive",
    :"visible"
  ]

  @type t :: %__MODULE__{
    :"perkHash" => integer(),
    :"iconPath" => String.t,
    :"isActive" => boolean(),
    :"visible" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyPerksDestinyPerkReference do
  def decode(value, _options) do
    value
  end
end

