# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyNodeSocketReplaceResponse do
  @moduledoc """
  This is a bit of an odd duck. Apparently, if talent nodes steps have this data, the game will go through on step activation and alter the first Socket it finds on the item that has a type matching the given socket type, inserting the indicated plug item.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"socketTypeHash",
    :"plugItemHash"
  ]

  @type t :: %__MODULE__{
    :"socketTypeHash" => integer(),
    :"plugItemHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyNodeSocketReplaceResponse do
  def decode(value, _options) do
    value
  end
end

