# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyObjectivePerkEntryDefinition do
  @moduledoc """
  Defines the conditions under which an intrinsic perk is applied while participating in an Objective.  These perks will generally not be benefit-granting perks, but rather a perk that modifies gameplay in some interesting way.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"perkHash",
    :"style"
  ]

  @type t :: %__MODULE__{
    :"perkHash" => integer(),
    :"style" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyObjectivePerkEntryDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"style", :struct, BungieNetAPI.Model.Object, options)
  end
end

