# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyHistoricalStatsDestinyLeaderboard do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"statId",
    :"entries"
  ]

  @type t :: %__MODULE__{
    :"statId" => String.t,
    :"entries" => [DestinyHistoricalStatsDestinyLeaderboardEntry]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyHistoricalStatsDestinyLeaderboard do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entries", :list, BungieNetAPI.Model.DestinyHistoricalStatsDestinyLeaderboardEntry, options)
  end
end

