# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyDefinition do
  @moduledoc """
  Provides common properties for destiny definitions.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hash",
    :"index",
    :"redacted"
  ]

  @type t :: %__MODULE__{
    :"hash" => integer(),
    :"index" => integer(),
    :"redacted" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyDefinition do
  def decode(value, _options) do
    value
  end
end

