# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDestinyItemSackBlockDefinition do
  @moduledoc """
  Some items are \&quot;sacks\&quot; - they can be \&quot;opened\&quot; to produce other items. This is information related to its sack status, mostly UI strings. Engrams are an example of items that are considered to be \&quot;Sacks\&quot;.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"detailAction",
    :"openAction",
    :"selectItemCount",
    :"vendorSackType",
    :"openOnAcquire"
  ]

  @type t :: %__MODULE__{
    :"detailAction" => String.t,
    :"openAction" => String.t,
    :"selectItemCount" => integer(),
    :"vendorSackType" => String.t,
    :"openOnAcquire" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDestinyItemSackBlockDefinition do
  def decode(value, _options) do
    value
  end
end

