# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition do
  @moduledoc """
  This is the position and other data related to nodes in the activity graph that you can click to launch activities. An Activity Graph node will only have one active Activity at a time, which will determine the activity to be launched (and, unless overrideDisplay information is provided, will also determine the tooltip and other UI related to the node)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nodeId",
    :"overrideDisplay",
    :"position",
    :"featuringStates",
    :"activities"
  ]

  @type t :: %__MODULE__{
    :"nodeId" => integer(),
    :"overrideDisplay" => Object,
    :"position" => Object,
    :"featuringStates" => [DestinyDefinitionsDirectorDestinyActivityGraphNodeFeaturingStateDefinition],
    :"activities" => [DestinyDefinitionsDirectorDestinyActivityGraphNodeActivityDefinition]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeDefinition do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"overrideDisplay", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"position", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"featuringStates", :list, BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeFeaturingStateDefinition, options)
    |> deserialize(:"activities", :list, BungieNetAPI.Model.DestinyDefinitionsDirectorDestinyActivityGraphNodeActivityDefinition, options)
  end
end

