# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneActivity do
  @moduledoc """
  A milestone may have one or more conceptual Activities associated with it, and each of those conceptual activities could have a variety of variants, modes, tiers, what-have-you. Our attempts to determine what qualifies as a conceptual activity are, unfortunately, janky. So if you see missing modes or modes that don&#39;t seem appropriate to you, let us know and I&#39;ll buy you a beer if we ever meet up in person.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"activityHash",
    :"modifierHashes",
    :"variants",
    :"activityModeHash",
    :"activityModeType"
  ]

  @type t :: %__MODULE__{
    :"activityHash" => integer(),
    :"modifierHashes" => [integer()],
    :"variants" => [DestinyMilestonesDestinyPublicMilestoneActivityVariant],
    :"activityModeHash" => integer(),
    :"activityModeType" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneActivity do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"variants", :list, BungieNetAPI.Model.DestinyMilestonesDestinyPublicMilestoneActivityVariant, options)
  end
end

