# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyRequestsDestinyItemTransferRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemReferenceHash",
    :"stackSize",
    :"transferToVault",
    :"itemId",
    :"characterId",
    :"membershipType"
  ]

  @type t :: %__MODULE__{
    :"itemReferenceHash" => integer(),
    :"stackSize" => integer(),
    :"transferToVault" => boolean(),
    :"itemId" => integer(),
    :"characterId" => integer(),
    :"membershipType" => BungieMembershipType
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyRequestsDestinyItemTransferRequest do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"membershipType", :struct, BungieNetAPI.Model.BungieMembershipType, options)
  end
end

