# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesInventoryDestinyInventoryComponent do
  @moduledoc """
  A list of minimal information for items in an inventory: be it a character&#39;s inventory, or a Profile&#39;s inventory. (Note that the Vault is a collection of inventory buckets in the Profile&#39;s inventory)  Inventory Items returned here are in a flat list, but importantly they have a bucketHash property that indicates the specific inventory bucket that is holding them. These buckets constitute things like the separate sections of the Vault, the user&#39;s inventory slots, etc. See DestinyInventoryBucketDefinition for more info.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"items"
  ]

  @type t :: %__MODULE__{
    :"items" => [DestinyEntitiesItemsDestinyItemComponent]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesInventoryDestinyInventoryComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"items", :list, BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemComponent, options)
  end
end

