# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemRenderComponent do
  @moduledoc """
  Many items can be rendered in 3D. When you request this block, you will obtain the custom data needed to render this specific instance of the item.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"useCustomDyes",
    :"artRegions"
  ]

  @type t :: %__MODULE__{
    :"useCustomDyes" => boolean(),
    :"artRegions" => %{optional(String.t) => integer()}
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesItemsDestinyItemRenderComponent do
  def decode(value, _options) do
    value
  end
end

