# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.DestinyEntitiesCharactersDestinyCharacterRenderComponent do
  @moduledoc """
  Only really useful if you&#39;re attempting to render the character&#39;s current appearance in 3D, this returns a bare minimum of information, pre-aggregated, that you&#39;ll need to perform that rendering. Note that you need to combine this with other 3D assets and data from our servers.  Examine the Javascript returned by https://bungie.net/sharedbundle/spasm to see how we use this data, but be warned: the rabbit hole goes pretty deep.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"customDyes",
    :"customization",
    :"peerView"
  ]

  @type t :: %__MODULE__{
    :"customDyes" => [DestinyDyeReference],
    :"customization" => Object,
    :"peerView" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.DestinyEntitiesCharactersDestinyCharacterRenderComponent do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"customDyes", :list, BungieNetAPI.Model.DestinyDyeReference, options)
    |> deserialize(:"customization", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"peerView", :struct, BungieNetAPI.Model.Object, options)
  end
end

