# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ForumPostSearchResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"relatedPosts",
    :"authors",
    :"groups",
    :"searchedTags",
    :"polls",
    :"recruitmentDetails",
    :"availablePages",
    :"results",
    :"totalResults",
    :"hasMore",
    :"query",
    :"replacementContinuationToken",
    :"useTotalResults"
  ]

  @type t :: %__MODULE__{
    :"relatedPosts" => [ForumPostResponse],
    :"authors" => [UserGeneralUser],
    :"groups" => [GroupsV2GroupResponse],
    :"searchedTags" => [TagsModelsContractsTagResponse],
    :"polls" => [ForumPollResponse],
    :"recruitmentDetails" => [ForumForumRecruitmentDetail],
    :"availablePages" => integer(),
    :"results" => [ForumPostResponse],
    :"totalResults" => integer(),
    :"hasMore" => boolean(),
    :"query" => QueriesPagedQuery,
    :"replacementContinuationToken" => String.t,
    :"useTotalResults" => boolean()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ForumPostSearchResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"relatedPosts", :list, BungieNetAPI.Model.ForumPostResponse, options)
    |> deserialize(:"authors", :list, BungieNetAPI.Model.UserGeneralUser, options)
    |> deserialize(:"groups", :list, BungieNetAPI.Model.GroupsV2GroupResponse, options)
    |> deserialize(:"searchedTags", :list, BungieNetAPI.Model.TagsModelsContractsTagResponse, options)
    |> deserialize(:"polls", :list, BungieNetAPI.Model.ForumPollResponse, options)
    |> deserialize(:"recruitmentDetails", :list, BungieNetAPI.Model.ForumForumRecruitmentDetail, options)
    |> deserialize(:"results", :list, BungieNetAPI.Model.ForumPostResponse, options)
    |> deserialize(:"query", :struct, BungieNetAPI.Model.QueriesPagedQuery, options)
  end
end

