# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ForumPollResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"topicId",
    :"results",
    :"totalVotes"
  ]

  @type t :: %__MODULE__{
    :"topicId" => integer(),
    :"results" => [ForumPollResult],
    :"totalVotes" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ForumPollResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"results", :list, BungieNetAPI.Model.ForumPollResult, options)
  end
end

