# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.ForumForumRecruitmentDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"topicId",
    :"microphoneRequired",
    :"intensity",
    :"tone",
    :"approved",
    :"conversationId",
    :"playerSlotsTotal",
    :"playerSlotsRemaining",
    :"Fireteam",
    :"kickedPlayerIds"
  ]

  @type t :: %__MODULE__{
    :"topicId" => integer(),
    :"microphoneRequired" => boolean(),
    :"intensity" => ForumForumRecruitmentIntensityLabel,
    :"tone" => ForumForumRecruitmentToneLabel,
    :"approved" => boolean(),
    :"conversationId" => integer(),
    :"playerSlotsTotal" => integer(),
    :"playerSlotsRemaining" => integer(),
    :"Fireteam" => [UserGeneralUser],
    :"kickedPlayerIds" => [integer()]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.ForumForumRecruitmentDetail do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"intensity", :struct, BungieNetAPI.Model.ForumForumRecruitmentIntensityLabel, options)
    |> deserialize(:"tone", :struct, BungieNetAPI.Model.ForumForumRecruitmentToneLabel, options)
    |> deserialize(:"Fireteam", :list, BungieNetAPI.Model.UserGeneralUser, options)
  end
end

