# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupV2ClanInfo do
  @moduledoc """
  This contract contains clan-specific group information. It does not include any investment data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"clanCallsign",
    :"clanBannerData"
  ]

  @type t :: %__MODULE__{
    :"clanCallsign" => String.t,
    :"clanBannerData" => GroupsV2ClanBanner
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupV2ClanInfo do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"clanBannerData", :struct, BungieNetAPI.Model.GroupsV2ClanBanner, options)
  end
end

