# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupV2ClanInfoAndInvestment do
  @moduledoc """
  The same as GroupV2ClanInfo, but includes any investment data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"d2ClanProgressions",
    :"clanCallsign",
    :"clanBannerData"
  ]

  @type t :: %__MODULE__{
    :"d2ClanProgressions" => %{optional(String.t) => DestinyDestinyProgression},
    :"clanCallsign" => String.t,
    :"clanBannerData" => GroupsV2ClanBanner
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupV2ClanInfoAndInvestment do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"d2ClanProgressions", :map, BungieNetAPI.Model.DestinyDestinyProgression, options)
    |> deserialize(:"clanBannerData", :struct, BungieNetAPI.Model.GroupsV2ClanBanner, options)
  end
end

