# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupEditAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"about",
    :"motto",
    :"theme",
    :"avatarImageIndex",
    :"tags",
    :"isPublic",
    :"membershipOption",
    :"isPublicTopicAdminOnly",
    :"allowChat",
    :"chatSecurity",
    :"callsign",
    :"locale",
    :"homepage",
    :"enableInvitationMessagingForAdmins",
    :"defaultPublicity"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"about" => String.t,
    :"motto" => String.t,
    :"theme" => String.t,
    :"avatarImageIndex" => integer(),
    :"tags" => String.t,
    :"isPublic" => boolean(),
    :"membershipOption" => integer(),
    :"isPublicTopicAdminOnly" => boolean(),
    :"allowChat" => boolean(),
    :"chatSecurity" => integer(),
    :"callsign" => String.t,
    :"locale" => String.t,
    :"homepage" => integer(),
    :"enableInvitationMessagingForAdmins" => boolean(),
    :"defaultPublicity" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupEditAction do
  def decode(value, _options) do
    value
  end
end

