# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2HostGuidedGamesPermissionLevel do
  @moduledoc """
  Used for setting the guided game permission level override (admins and founders can always host guided games).
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2HostGuidedGamesPermissionLevel do
  def decode(value, _options) do
    value
  end
end

