# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupApplicationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resolution"
  ]

  @type t :: %__MODULE__{
    :"resolution" => GroupsV2GroupApplicationResolveState
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupApplicationResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"resolution", :struct, BungieNetAPI.Model.GroupsV2GroupApplicationResolveState, options)
  end
end

