# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupMembershipBase do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"group"
  ]

  @type t :: %__MODULE__{
    :"group" => GroupsV2GroupV2
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupMembershipBase do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"group", :struct, BungieNetAPI.Model.GroupsV2GroupV2, options)
  end
end

