# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupFeatures do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"maximumMembers",
    :"maximumMembershipsOfGroupType",
    :"capabilities",
    :"membershipTypes",
    :"invitePermissionOverride",
    :"updateCulturePermissionOverride",
    :"hostGuidedGamePermissionOverride",
    :"updateBannerPermissionOverride",
    :"joinLevel"
  ]

  @type t :: %__MODULE__{
    :"maximumMembers" => integer(),
    :"maximumMembershipsOfGroupType" => integer(),
    :"capabilities" => GroupsV2Capabilities,
    :"membershipTypes" => [BungieMembershipType],
    :"invitePermissionOverride" => boolean(),
    :"updateCulturePermissionOverride" => boolean(),
    :"hostGuidedGamePermissionOverride" => Object,
    :"updateBannerPermissionOverride" => boolean(),
    :"joinLevel" => Object
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupFeatures do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"capabilities", :struct, BungieNetAPI.Model.GroupsV2Capabilities, options)
    |> deserialize(:"membershipTypes", :list, BungieNetAPI.Model.BungieMembershipType, options)
    |> deserialize(:"hostGuidedGamePermissionOverride", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"joinLevel", :struct, BungieNetAPI.Model.Object, options)
  end
end

