# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupBan do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"groupId",
    :"lastModifiedBy",
    :"createdBy",
    :"dateBanned",
    :"dateExpires",
    :"comment",
    :"bungieNetUserInfo",
    :"destinyUserInfo"
  ]

  @type t :: %__MODULE__{
    :"groupId" => integer(),
    :"lastModifiedBy" => UserUserInfoCard,
    :"createdBy" => UserUserInfoCard,
    :"dateBanned" => DateTime.t,
    :"dateExpires" => DateTime.t,
    :"comment" => String.t,
    :"bungieNetUserInfo" => UserUserInfoCard,
    :"destinyUserInfo" => UserUserInfoCard
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupBan do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"lastModifiedBy", :struct, BungieNetAPI.Model.UserUserInfoCard, options)
    |> deserialize(:"createdBy", :struct, BungieNetAPI.Model.UserUserInfoCard, options)
    |> deserialize(:"bungieNetUserInfo", :struct, BungieNetAPI.Model.UserUserInfoCard, options)
    |> deserialize(:"destinyUserInfo", :struct, BungieNetAPI.Model.UserUserInfoCard, options)
  end
end

