# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupOptionalConversationAddRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"chatName",
    :"chatSecurity"
  ]

  @type t :: %__MODULE__{
    :"chatName" => String.t,
    :"chatSecurity" => GroupsV2ChatSecuritySetting
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupOptionalConversationAddRequest do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"chatSecurity", :struct, BungieNetAPI.Model.GroupsV2ChatSecuritySetting, options)
  end
end

