# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupBanRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"comment",
    :"length"
  ]

  @type t :: %__MODULE__{
    :"comment" => String.t,
    :"length" => IgnoresIgnoreLength
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupBanRequest do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"length", :struct, BungieNetAPI.Model.IgnoresIgnoreLength, options)
  end
end

