# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.GroupsV2GroupQuery do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"groupType",
    :"creationDate",
    :"sortBy",
    :"groupMemberCountFilter",
    :"localeFilter",
    :"tagText",
    :"itemsPerPage",
    :"currentPage",
    :"requestContinuationToken"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"groupType" => GroupsV2GroupType,
    :"creationDate" => GroupsV2GroupDateRange,
    :"sortBy" => GroupsV2GroupSortBy,
    :"groupMemberCountFilter" => integer(),
    :"localeFilter" => String.t,
    :"tagText" => String.t,
    :"itemsPerPage" => integer(),
    :"currentPage" => integer(),
    :"requestContinuationToken" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.GroupsV2GroupQuery do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"groupType", :struct, BungieNetAPI.Model.GroupsV2GroupType, options)
    |> deserialize(:"creationDate", :struct, BungieNetAPI.Model.GroupsV2GroupDateRange, options)
    |> deserialize(:"sortBy", :struct, BungieNetAPI.Model.GroupsV2GroupSortBy, options)
  end
end

