# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.IgnoresIgnoreResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"isIgnored",
    :"ignoreFlags"
  ]

  @type t :: %__MODULE__{
    :"isIgnored" => boolean(),
    :"ignoreFlags" => IgnoresIgnoreStatus
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.IgnoresIgnoreResponse do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ignoreFlags", :struct, BungieNetAPI.Model.IgnoresIgnoreStatus, options)
  end
end

