# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.PartnershipsPublicPartnershipDetail do
  @moduledoc """
  All the partnership info that&#39;s fit to expose externally, if we care to do so.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"partnerType",
    :"identifier",
    :"name",
    :"icon"
  ]

  @type t :: %__MODULE__{
    :"partnerType" => PartnershipsPartnershipType,
    :"identifier" => String.t,
    :"name" => String.t,
    :"icon" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.PartnershipsPublicPartnershipDetail do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"partnerType", :struct, BungieNetAPI.Model.PartnershipsPartnershipType, options)
  end
end

