# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.TrendingTrendingEntry do
  @moduledoc """
  The list entry view for trending items. Returns just enough to show the item on the trending page.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"weight",
    :"isFeatured",
    :"identifier",
    :"entityType",
    :"displayName",
    :"tagline",
    :"image",
    :"startDate",
    :"endDate",
    :"link",
    :"webmVideo",
    :"mp4Video",
    :"featureImage",
    :"items"
  ]

  @type t :: %__MODULE__{
    :"weight" => float(),
    :"isFeatured" => boolean(),
    :"identifier" => String.t,
    :"entityType" => Object,
    :"displayName" => String.t,
    :"tagline" => String.t,
    :"image" => String.t,
    :"startDate" => DateTime.t,
    :"endDate" => DateTime.t,
    :"link" => String.t,
    :"webmVideo" => String.t,
    :"mp4Video" => String.t,
    :"featureImage" => String.t,
    :"items" => [TrendingTrendingEntry]
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.TrendingTrendingEntry do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entityType", :struct, BungieNetAPI.Model.Object, options)
    |> deserialize(:"items", :list, BungieNetAPI.Model.TrendingTrendingEntry, options)
  end
end

