# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.TrendingTrendingEntryDestinyActivity do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"activityHash",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"activityHash" => integer(),
    :"status" => DestinyActivitiesDestinyPublicActivityStatus
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.TrendingTrendingEntryDestinyActivity do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, BungieNetAPI.Model.DestinyActivitiesDestinyPublicActivityStatus, options)
  end
end

