# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.TrendingTrendingEntryCommunityStream do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"image",
    :"title",
    :"partnershipIdentifier",
    :"partnershipType"
  ]

  @type t :: %__MODULE__{
    :"image" => String.t,
    :"title" => String.t,
    :"partnershipIdentifier" => String.t,
    :"partnershipType" => PartnershipsPartnershipType
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.TrendingTrendingEntryCommunityStream do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"partnershipType", :struct, BungieNetAPI.Model.PartnershipsPartnershipType, options)
  end
end

