# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.TrendingTrendingCategory do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categoryName",
    :"entries",
    :"categoryId"
  ]

  @type t :: %__MODULE__{
    :"categoryName" => String.t,
    :"entries" => SearchResultOfTrendingEntry,
    :"categoryId" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.TrendingTrendingCategory do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entries", :struct, BungieNetAPI.Model.SearchResultOfTrendingEntry, options)
  end
end

