# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.TrendingTrendingEntryDestinyItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"itemHash"
  ]

  @type t :: %__MODULE__{
    :"itemHash" => integer()
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.TrendingTrendingEntryDestinyItem do
  def decode(value, _options) do
    value
  end
end

