# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.TrendingTrendingDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"identifier",
    :"entityType",
    :"news",
    :"support",
    :"destinyItem",
    :"destinyActivity",
    :"destinyRitual",
    :"creation",
    :"stream"
  ]

  @type t :: %__MODULE__{
    :"identifier" => String.t,
    :"entityType" => TrendingTrendingEntryType,
    :"news" => TrendingTrendingEntryNews,
    :"support" => TrendingTrendingEntrySupportArticle,
    :"destinyItem" => TrendingTrendingEntryDestinyItem,
    :"destinyActivity" => TrendingTrendingEntryDestinyActivity,
    :"destinyRitual" => TrendingTrendingEntryDestinyRitual,
    :"creation" => TrendingTrendingEntryCommunityCreation,
    :"stream" => TrendingTrendingEntryCommunityStream
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.TrendingTrendingDetail do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entityType", :struct, BungieNetAPI.Model.TrendingTrendingEntryType, options)
    |> deserialize(:"news", :struct, BungieNetAPI.Model.TrendingTrendingEntryNews, options)
    |> deserialize(:"support", :struct, BungieNetAPI.Model.TrendingTrendingEntrySupportArticle, options)
    |> deserialize(:"destinyItem", :struct, BungieNetAPI.Model.TrendingTrendingEntryDestinyItem, options)
    |> deserialize(:"destinyActivity", :struct, BungieNetAPI.Model.TrendingTrendingEntryDestinyActivity, options)
    |> deserialize(:"destinyRitual", :struct, BungieNetAPI.Model.TrendingTrendingEntryDestinyRitual, options)
    |> deserialize(:"creation", :struct, BungieNetAPI.Model.TrendingTrendingEntryCommunityCreation, options)
    |> deserialize(:"stream", :struct, BungieNetAPI.Model.TrendingTrendingEntryCommunityStream, options)
  end
end

