# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.UserUserMembership do
  @moduledoc """
  Very basic info about a user as returned by the Account server.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"membershipType",
    :"membershipId",
    :"displayName"
  ]

  @type t :: %__MODULE__{
    :"membershipType" => Object,
    :"membershipId" => integer(),
    :"displayName" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.UserUserMembership do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"membershipType", :struct, BungieNetAPI.Model.Object, options)
  end
end

