# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.UserGeneralUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"membershipId",
    :"uniqueName",
    :"normalizedName",
    :"displayName",
    :"profilePicture",
    :"profileTheme",
    :"userTitle",
    :"successMessageFlags",
    :"isDeleted",
    :"about",
    :"firstAccess",
    :"lastUpdate",
    :"legacyPortalUID",
    :"context",
    :"psnDisplayName",
    :"xboxDisplayName",
    :"fbDisplayName",
    :"showActivity",
    :"locale",
    :"localeInheritDefault",
    :"lastBanReportId",
    :"showGroupMessaging",
    :"profilePicturePath",
    :"profilePictureWidePath",
    :"profileThemeName",
    :"userTitleDisplay",
    :"statusText",
    :"statusDate",
    :"profileBanExpire",
    :"blizzardDisplayName"
  ]

  @type t :: %__MODULE__{
    :"membershipId" => integer(),
    :"uniqueName" => String.t,
    :"normalizedName" => String.t,
    :"displayName" => String.t,
    :"profilePicture" => integer(),
    :"profileTheme" => integer(),
    :"userTitle" => integer(),
    :"successMessageFlags" => integer(),
    :"isDeleted" => boolean(),
    :"about" => String.t,
    :"firstAccess" => DateTime.t,
    :"lastUpdate" => DateTime.t,
    :"legacyPortalUID" => integer(),
    :"context" => UserUserToUserContext,
    :"psnDisplayName" => String.t,
    :"xboxDisplayName" => String.t,
    :"fbDisplayName" => String.t,
    :"showActivity" => boolean(),
    :"locale" => String.t,
    :"localeInheritDefault" => boolean(),
    :"lastBanReportId" => integer(),
    :"showGroupMessaging" => boolean(),
    :"profilePicturePath" => String.t,
    :"profilePictureWidePath" => String.t,
    :"profileThemeName" => String.t,
    :"userTitleDisplay" => String.t,
    :"statusText" => String.t,
    :"statusDate" => DateTime.t,
    :"profileBanExpire" => DateTime.t,
    :"blizzardDisplayName" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.UserGeneralUser do
  import BungieNetAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"context", :struct, BungieNetAPI.Model.UserUserToUserContext, options)
  end
end

