# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule BungieNetAPI.Model.UserModelsUserAlias do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cachePrefix"
  ]

  @type t :: %__MODULE__{
    :"cachePrefix" => String.t
  }
end

defimpl Poison.Decoder, for: BungieNetAPI.Model.UserModelsUserAlias do
  def decode(value, _options) do
    value
  end
end

